### ISSUE TITLE
Glow Collar:  Leash Settings, Turn

### ISSUE THREAD

**Issue by KiraShinx** [OpenCollar/opencollar#1028]
On the glow collar, available today at the open collar temple vendors, the turn towards leasher is not align correctly. wearer turns 270 deg. towards leasher, if pulled behind leasher.

[12:32:13] Glow Collar: 

OpenCollar Version: 6.5.0 (170330.100000)
Origin: OpenCollar [Official]

**Comment by WendyStarfall** [comment]
Make sure that the Turn option is indeed enabled (setting: ``LEASH=turn~1``)

Turning towards the leasher isn't a very exact science. Most of time you get them turned in an "OK" manner but in order to accurately position an avatar, we would have to sit her on an object and position the object.

Other factors that have influence on the visual experience is when the leashed avatar moves on her own during the pull or AOs that displace the avatar to face a direction that she isn't technically turned to.

This happens in the ``at_target`` function, the relevant lines are 798 and 799 and can be seen [here](https://github.com/VirtualDisgrace/opencollar/blob/master/src/collar/oc_leash.lsl#L791-L802).

**Comment by WendyStarfall** [comment]
I couldn't a reproduce an exact 270° but had mixed results. Let's see what the future brings us in actual LSL functions to position avatars.
