### ISSUE TITLE
Milestone 6.6 - Use fewer HTTP requests and use them less often

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#1032]
**Version/s:** ``all versions lower than 6.6``

⚠ MANDATORY ⚠

We are hitting some limits with HTTP requests. The positive bit here is that recent versions of OpenCollar Six became unexpectedly popular and far more widespread than OpenCollar 3.7 to 3.9.

The bad news is that this throttles our heartbeat. I have already attempted to alternate hosts across versions for our version control and emergency news system but this is by no means a viable solution in the long run. We have the opportunity to make use of the virtualdisgrace.com infrastructure, but considering that hosting costs money, we have to ensure that their web credentials are secure.

To achieve that, we will have to explore alternative licensing for web connect script/s. We want to ideally keep this in only a single script, provide the un-compiled source on this public repository (without credentials) and ship a secure version (with credentials) ready-compiled on Second Life®.

There will be the inevitable uproar among some pseudo freedom fighter users (but those guys never had to pay the bills) and I'm happy to resign my role and fully accept whatever melodramatic blame comes our way, because without those changes, this project will have no future progress.

I will express this in some greater detail on the OpenCollar.at (Austria) blog when the time is ready.

**Comment by WendyStarfall** [comment]
Okay, so far so good. I've had some time to contemplate whether to, even add a dedicated web connect script, or to replace one of the existing scripts. In this case, I believe the better choice is to replace ``oc_sys``.

``oc_sys`` is unnecessarily crammed full of HTTP requests and in order to have meaningful web connect features, it would have to be thouroughly cleaned up (or refactored) anyway. My decision is as follows:

``oc_sys`` will be replaced with a new script that is composed from scratch. Given the non-essential nature of ``oc_sys`` (the core plugin in the root is ``oc_com`` and not ``oc_sys``) will make it a great candidate. A device can also exist without ``oc_sys`` if users choose to run their collar that way, and in case they should disagree with a permissive open source license style and prefer to keep the selection of scripts as purely "free software".

The ``oc_sys`` replacement **must be licensed permissively** because we need to be able to sub-license it to some extent, in order to be able to scale. At the same time, we want to prevent overly zealous, new scripters from entangling themselves into financial issues over some tinker toy in everyone's favorite virtual world.

**Comment by illiara** [comment]
I'm not entirely sure which http requests you're talking about here, I'm not that familiar with the code for OpenCollar. I was looking up the reason for the removal of the OpenCollar Database a couple of years ago (or well, more than a couple!) and then stumbled upon this issue here. 

I was wondering if you've ever considered looking at solutions such as AWS Lambda, you don't have to think about issues like scaling or managing servers as Amazon's infrastructure takes care of it. It will all run in parallel so there won't be any block ups either. The best part of it is that you pay for what you use. 

I'm also not familiar with your programming background, but it's very simple to get started with. I've just been playing around with the [serverless](http://serverless.com) framework. I just wanted a quick api based database and didn't feel like provisioning a VPS, plus I wanted to try something new 😊 I must say it's easier that I expected it to be. It's simply a matter of configuration to get it all up and running and there's plenty of examples and documentation out there. All you have to do then is write the code you need in NodeJS, of course there are other ways and languages to run AWS Lamba though. 

I'm not sure if this is a viable option, I have no idea how much traffic/requests you need to handle but I think it's worth taking a look at and maybe it might bring back that OpenCollar Database I liked so much!

Just my 2 cents, maybe I'm going way off topic here!

**Comment by XenHat** [comment]
While AWS is an extremely good hosting solution, it is not cheap for the amount of requests OpenCollar would be getting. OpenCollar is mostly donation based, and that solution would be, I believe, simply unaffordable.
