### ISSUE TITLE
Relay mode switching commands other than "off" don't work

### ISSUE THREAD

**Issue by stawberri** [OpenCollar/opencollar#1063]
I was trying out commands I found on [opencollar.at](http://www.opencollar.at/relay.html), and `<prefix> relay auto` and `<prefix> relay ask` don't seem to work. `<prefix> relay off` works.

I thought that the issue might be here:

https://github.com/VirtualDisgrace/opencollar/blob/26d0314832c4ba9f7231e726d02fa8c504b3aa89/src/collar/oc_relay.lsl#L394-L397

Changing `sChangetype` to `sChangevalue` seems to make commands start working, but it breaks the menu.

I think this might be a little too complicated for me to figure out! I hope it won't be too much of a hassle to fix.

---

**Edit**: I asked about this in group chat (leading to a lot of confusion--sorry), and Otto told me that I could use `<prefix> relay auto on` and `<prefix> relay ask on` for now. If you're another user looking at this issue, maybe you'll find this information helpful?

**Comment by GarvinTwine** [comment]
Yeah, I kinda forgot to test the chat commands when doing the menu ones I guess.
one line added here should fix this though:
https://github.com/VirtualDisgrace/opencollar/blob/26d0314832c4ba9f7231e726d02fa8c504b3aa89/src/collar/oc_relay.lsl#L373-L376
add 377 as
`if (index == -1) sChangetype = sStr;`

That's because the menu sends the commands as `mode on|off` and when the second part of this command is missing the sChangevalue gets truncated for the last character due to a missing space.

**Comment by SoranaBarbosa** [comment]
I am also having issues with the relay.  I have mine set to ask, but I just keep getting the blue popup window with yes/no/block over and over again.  There is also no name for the object in that window.
