### ISSUE TITLE
Titler: Cool graph feature by @george-black

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#1070]
**Version:** ``𝓟𝓮𝓪𝓷𝓾𝓽 ₁₇₁₂₁₄.₁``

@george-black offered a PR with a cool feature for our titler app:

A graph that can show a percentage bar and a title for it, and it looks like that!

![2017-12-15_0839](https://user-images.githubusercontent.com/1100007/34031844-9223f8a4-e173-11e7-9083-dd01c4f00465.png)

There is a special command for it: ``<prefix> graph <percentage> <title>``

Like in my sample above, it would be: ``we graph 68 in love``

The new feature is included with ``peanut`` version releases and als in the Legacy Apps bundle!

Thank you @george-black ♥

**Comment by Saraeva** [comment]
Is it possible to make it do decimals and fractions? I wanted to make it say "99 44/100% Pure" but, it turned out to be "99% 44/100% Pure". And decimals get dropped altogether. I don't know much about coding though.  I've spoken to @george-black about it, and wasn't sure if this should be a new issue since this one is labeled as completed. Please advise.
