### ISSUE TITLE
#rlv folder access

### ISSUE THREAD

**Issue by Xiarettah** [OpenCollar/opencollar#19]
The general idea behind the #rlv folder is to allow owners to use the subs restraints.
The last three updaters 3.915 3.916 and 3.917 (all official releases in the month of September) do not show the status of the individual restarint items, thus making it impossible for the owner to identify the restraints status.
I have already advised my groups not to use new updaters any more for the time being and stay with vs 3.910

**Comment by WendyStarfall** [comment]
Our problem here is that some unicode must have gotten lost along the way; probably caused by a desktop editor failing to interpret some of it. The #RLV however does not indicate restraint status, it tells about folders, subfolders, items in folders and if those are within a root folder or sub folder or worn or partially worn etc..

Probably we need better documentation for this! lol

The missing unicode characters are all back from betas 3.918 and greater, the next main release 3.930 is going to have this fix as well. I have been spending a lot of time on editing menus and right now giving 3.930 the final polish.
