### ISSUE TITLE
Missing Note Card for the updater.

### ISSUE THREAD

**Issue by AndriaArun** [OpenCollar/opencollar#243]
i like the new OpenCollar updater system. But their are somethings that were left out. the updater options "standard" and "basic" need to be defined clearly. 
as i recently discoverd the animator isn't included in the "basic" update. wich is odd since animations are a core feature in the collar.
the current NC in the updater dose not explain how to use the updater, its just a short "how to" use the collar. but nothing on how to use the updater. though using the updater is pretty easy, the NC should only expain what each option, "standard", "basic", "Custom" & "Devolper" is so people know which one is best for them

**Comment by WendyStarfall** [comment]
I would first like to explain what was in place at the time this issue was raised, meaning all the time before the 17th of May.
- If users get an updater from our network vendors, they received an updater notecard.
- If users get an updater through online markets, like Marketplace or Primbay, they receive a notecard as well.
- If users get an updater handed to them by a third party, the update sequence has a Help feature that directs to a dedicated "update" section on our website, including FAQ.

This is how the notecard, or read me if so be it, is currently distributed. The only time a person will not get a physical notecard directly from us is if they don't get the software box directly from us. Also the individual manual sections explain if the individual feature is optional.

**_There for the title of this issue is already misleading._** :frowning:

Now let's take a look at the installation sequence itself.
- The user navigates to the Help/About menu and clicks Update to initiate.
- The first layer of documentation appears, explaining basic information how updates on SL work in general.

> 3 Golden Rules for Updates:
> 
> 1.Create a Backup
> 2.Rezzed is safer than Worn
> 3.Low Lag regions make happy Updates
> 
> (These rules apply to any kind of scripted item, not just collars or bondage and kink items!)
> 
> ATTENTION: Do not rez any other collars till the update has started.
> 
> Ready?
- Users can now either cancel with "No" or continue with "Yes" which leads them to select their preferred installation method: Standard, Basic, Custom or Developer. These are explained in the menu dialog. If we changed bundles for the individual version update, this had always been adjusted. Developer is for developers. If a person isn't a developer they can ask one of us.

> Basic: "Just the basic modular collar framework and essential core features."

And we arrive at where the real dog is buried here. What one user sees as "core", another user sees as optional feature and at the same time a developer might see it as neither. The definition of core as of 3.96x is as follows:
- The framework to create menus, handle authorization and manage plugins.

> That means auth, dialog, listener, settings, main and update
- The essential features for the individual design of the collar.

> A kitty or cowbell collar will keep it's bell. One that relies on a label, will also keep and run it.
- The basic simulation of a collar.

> We have a bondage collar, an accessory wrapped around someones neck which can be locked and leashed. For another person to be able adjusting fit, we have our appearance plugin.

The pose and couple animation engine is, according to user feedback, not a core deal. It simply isn't for every cat, dog, brony or horse avatar because they don't move and pose like humans do. To have a streamlined system, we don't need those users to carry half a dozen plugins in their device which they will not only never need but also are non essential for the cosmetic and _basic_ simulation of the thingy around their necks, which is what a users gets if the choice was even _Basic_.

To summarize this:
- The installation methods are properly defined in consideration of avoiding walls of text and the 512 character dialog limitation.
- Animations are not basic feature to simulate a collar according to user feedback apart from this issue.
- The notecard in the update contents is the quick manual to be installed in the device, the updater itself is distributed with documentation or provides a link to yet more detailed documentation on the web.
- The notecard addresses the summary of user queries since API version 3.7

How updates and installations will look like past 3.96x is yet to be discussed. Personally, I would like to stick to the 2011 myCollar study where we learn that distributing a much smaller library of plugins would be favourable. To quote Nandana:

> Share the load. Unlike OC, which takes on responsibility for distributing a large number of plugins (e.g. badwords, bell, keyholder, etc), myCollar will come with just the basics. If someone wants to add a feature, we'll help them write it as a plugin and distribute it under their name, but we're very unlikely to add it into the core. That way the plugin author gets the glory, as well as the bug reports.

An approach like this could also mean for our updates to work in a way of: "Just click START."
