### ISSUE TITLE
Item links to clothes layers don't work with smart strip

### ISSUE THREAD

**Issue by Ivanneth** [OpenCollar/opencollar#244]
Smart strip only works if the cloths layer in #RLV is a real item...not a link.

Having shoes in a folder and creating links to the two attachment items, feet shape layer and alpha doesn't work with smart strip. It works fine with "browser #RLV".

Using links to the feet shape layer, attachments and alpha...and adding a dummy shoes layer as real item works too (given that both layers are worn before)

Using links to attachments and alpha but copying the real feet shape layer works also. 

Making direct copies of all items works of course too. 

So it's really only the link to the layer that causes problems.

First question...is that intentional? If it is then it probably should be mentioned in the help-notecard.

Problems this could create:
If the shoes are for example no-copy you can't put them in two different #RLV outfits. Links are a good way around that. (Not to mention that some might prefer organizing their items in other places that #RLV with their own system). Workaround for now is putting a copy of the dummy layer in the folder as well..and wear two layers.

Expected behaviour:
Either that links work...or that it is mentioned in the help notecard.

**Comment by SatomiAhn** [comment]
Hello. The collar has no way to tell whether an item is a link or the actual item.
To me it is a bug in RLV implementation (in the viewer).

I was able to reproduce this faulty behavior in Firestorm (RLVa). So this should be reported to Firestorm's bugtracker or to RLVa's (maybe the better place, but then it would be a good idea to test with the reference RLVa viewer first, i.e. Catznip).

**Comment by SilkieSabra** [comment]
This was clarified in the manual here:  http://www.opencollar.at/folders.html
"_NOTE_ Smart Strip can work with linked items, only if the links are to an original copy that is also in #RLV shared folders. Remember that the strip function by itself does not use folders, it identifies the actual worn item. But smart strip requires that item to be in an RLV folder for the next operation, which is "detach with this everything in the same folder".  Therefore, the target of the link, the original worn item, must be in an RLV folder, and that folder must already be organized into groups that will be stripped with the item, since that is the folder the command will "see" when it strips the clothing layer.   Too confusing? don't use links then."

**Comment by WendyStarfall** [comment]
Thanks, silkie!
