### ISSUE TITLE
Wrong version reported

### ISSUE THREAD

**Issue by TucoSolo** [OpenCollar/opencollar#26]
**What is your Second Life name?**
Tuco Solo

**What steps will reproduce the problem?**
Update the collar to 3.931. Hit Get Version in the Help menu.

**What is the expected output?**
A chat line reading "OpenCollar: I am running OpenCollar version 3.931"

**What do you see instead?**
A chat line reading "OpenCollar: I am running OpenCollar version 3.930"

**What version of the collar (or other item) are you using?**
3.931 (updated from 3.930)

**Please provide any additional information below.**
The contents of ~version reads 3.931.
The Main dialog reports the version correctly: 3.931.

**Comment by TucoSolo** [comment]
Update:
A new rez seemed to halve solved the problem.

**Comment by WendyStarfall** [comment]
it's asset lag if the get version works right after the update or if you see it after picking the collar up and putting it on;

UPDATE: the version number in the main menu and Help/About menu text shows the same behaviour, we cannot work around this except by re-wear, re-log, picking it up after update installations - no worries tho, it doesn't mean the update failed, it just means that SL is being a slowpoke as usual =)

**Comment by WendyStarfall** [comment]
I'm closing this issue, looks like it works better lately but further investigating this is maybe not so important because the right version number reported isn't our indicator if an update took or failed, it is really just so users can learn about their version more easily if already wearing a collar and asking for support.
