### ISSUE TITLE
Add missing chat commands for rlvfolders.lsl

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#273]
Just about every feature in OpenCollar can be accessed with chat commands, except for one significant exception. There is currently no way through chat commands to add, remove, lock, or unlock RLV folders. For example:

```
/1 xxattachover:<folder_path>=force
/1 xxdetachthis:<folder_path>=force
/1 xxdetachthis:<folder_path>=add
/1 xxdetachallthis:<folder_path>=add
/1 xxdetachallthis_except:<folder_path>=add
/1 xxattachthis:<folder_path>=add
/1 xxattachallthis:<folder_path>=add
/1 xxattachallthis_except:<folder_path>=add
etc
```

All of the above chat commands currently do nothing. In addition to giving the owner another way of accessing the sub's RLV folders, it also opens up the possibility of creating huds or in world objects that can control the sub's outfits. To facilitate the latter two, a secondary suggestion would be to implement the rlv commands that query folders and worn clothing and attachment layers

```
/1 xxgetinv:<folder_path>=##
/1 xxgetinvworn:<folder_path>=##
/1 xxgetpath:<folder_path>=##
/1 xxfindfolder:<folder_path>=##
/1 xxgetoutfit:<folder_path>=##
/1 xxgetattached:<folder_path>=##
```

Note that the last two would be added to rlvundress, not rlvfolders

Implementing these commands would be trivial, since all that needs to be done is check the format and pass the command to rlvmain, unless we do not want to deal with the possibility of having restrictions for folders that do not exist, which would then require an additional check to see if the folder exists.

**Comment by SatomiAhn** [comment]
My humble opinion: since the number of RLV commands has become huge, maybe we should just have a generic way to enter any RLV command through the collar (which would behave like a relay operated by a human being).
This would remove a lot of existing adhoc code.

=force commands would be a no brainer
=channel commands should forward the viewer answer to the collar user in human readable form
(they actual input syntax shouldn't require an actual channel number to be specified)
=y/n/add/rem commands would go through rlvmain, specifying a source identifier different than those of existing plugins (maybe the UUID of the user?).

I have the feeling this could be added in the relay script with a little amount of lines of LSL code.

Advantage: full power of RLV through a really short code.
Drawback: no integration with existing menus (no way to enable/disable restrictions belonging to existing plugins and no way from the menus to enable/disable restrictions coming from the generic interface).

Menus should focus more in showing a simplified high-level view, where a single click could toggle several RLV restrictions at once when it makes sense and where it is not a goal to give access to every existing RLV command.

**Comment by XenHat** [comment]
I have already voiced my desire for a "Enter any command manually" option in the past, I think it would be a good thing to implement.

**Comment by ml132** [comment]
Let's suppose a sub has two owners: owner A only uses the collar through the dialog menu, and owner B only uses chat commands. Currently, each owner can remove restrictions set by the other owner in the same manner that he/she removes restrictions added by him/herself.

If we switch to a system where restrictions sent from chat are processed globally, owner B will be able to remove restrictions set by owner A, in addition to adding restrictions, just as before. Owner A will then have dialog menus that do not reflect the current state of the wearer's restrictions.

One possible solution to this is to change the way in which current restrictions are shown to a global system, and instead of toggles (Allow/Deny), have separate menus for adding and removing restrictions. I think this is a bit clunky and a large "quality of life" decrease for owner A.

Another solution is to make the restrictions set by owner B to behave like a relay, so owner A can press a button to remove all of them, but cannot remove them individually. Likewise, owner B cannot remove individual restrictions set by owner A, but can remove them simultaneously with a "clear" command. As someone who occasionally finds himself as either type of owner, this change would likely force me entirely into one of the two types.

Although I like Satomi's suggestion, I can't seem to come up with an implementation that I would consider an improvement from the user's perspective. Perhaps we could do a half measure, and have all queries and forcing RLV commands done through a generic method, but still keep restrictions tied to individual scripts.

**Comment by SatomiAhn** [comment]
This definitely requires some more thinking.

Concerning removing restrictions from other owners: maybe there would be two ways of removing a restriction. Either you remove only the lock you put yourself (bearing your UUID), or you remove all locks set by people with lesser or equal auth. Such a system would not be unlike the one for leashes and animations.
And maybe, it could be interesting to give the ability to send commands with a lower auth than you actually have, as to make it possible for secondaries to undo these.

Let me try to think this through and come up with a bunch of new "issues" for my proposals.

**Comment by ml132** [comment]
Right now, chat commands are sent to all scripts, and scripts with a matching command updates its memory and forwards an RLV command to rlvmain.

One possibility would be switching the order: chat commands go directly to rlvmain, and if executed, a message is sent to all other scripts informing them of the change. This allows every RLV command to be executed, regardless of whether it is implemented in the collar, while keeping the dialog menus up to date for relevant restrictions. I think this would remove some of the ad hoc code, while adding the feature of executing any rlv command from chat.

**Comment by XenHat** [comment]
I like ml132's idea, however sending directly to RLVmain right now would break the collar if the rlv bundle isn't installed.
A possible solution would be to keep a listener in the listen script, but kill that listener if rlvmain is found (since it would supersede listen and handle more)

**Comment by ml132** [comment]
I'd like to illustrate a possible implementation I was thinking about for this idea. Suppose I set a restriction in the rlvmisc menu with the dialog button. Rlvmisc will receive a link message (DIALOG_RESPONSE) from the button press and will produce a link message (COMMAND_NOAUTH) containing the rlv command to get authorized. Rlvmain will have to keep track of the authorization level for all current restrictions, and decide whether the authorized command is to be executed. In either case, it sends a link message (new integer codes?) indicating whether the command was executed.

Rlvmisc cannot create a new dialog menu until it receives this reply, meaning it must store the key of the avatar, as well as the corresponding restriction, for each avatar using the menu.

So to summarize, for this implementation:
Rlvmain needs to keep track of all current restrictions and their authorization level
All rlv scripts must now also keep track of users waiting for a dialog response
The dialog button presses behave just like chat commands with one extra layer of wrapping. The dialog button press is converted into a chat command(s), and after executing, a dialog menu is created.

Advantages:
  Removes code from RLV scripts that simply pass through RLV commands (forcing)
  Removes redundant code shared between chat commands and dialog button presses.
  Any RLV command can be sent as a chat command.

Disadvantages:
  rlvmain must keep track of all authorization levels for existing restrictions
  RLV scripts must wait for a linked message before creating a dialog menu
  Most chat commands will change into commands from the RLV protocol.
  Lots of work

I'm relatively new to OC scripting, so I'm quite certainly missing something, but this is the picture that I had in my head for the implementation.

**Comment by ml132** [comment]
So I was originally planning to just add the missing chat commands in a pull request. This new idea is something that is beyond what I feel capable of doing at the moment, but I would be willing to help if someone else is interested in working on this idea.

If not, does the OC developer community think adding the missing chat commands is an okay change to make while this larger idea is on hold?

**Comment by littlemousy** [comment]
I had another thought about chat commands for setting RLV, for in-world objects.  I thought it might make sense to use a different channel for these chat commands from objects for setting rlv restrictions.  I thought -1812221819 sounded like a good number, as long as its not used for anything already.

**Comment by ml132** [comment]
Currently, the collar can be accessed by in-world objects the same way that the owner hud does it, which is with the personal channel, or hud channel. Though after authorization, they are handled the same way as chat commands.

What would be the advantage of having a separate channel for in-world objects? Would the idea be to treat these restrictions like a private relay that only objects whose owners have access to the collar can use?

**Comment by steampilot** [comment]
About the topic of chat commands to add or remove clothes. I came across a porblem that bugs me.
Lets say we have smart strip on. and the folder structure looks like this
#rlv 
|--> body
|   |--> human(nostrip) 
|   |       //holds all the skins and shapes
|   |-->werewolf(nostrip)
|         //holds all the skin, shapes and attachments to form a werewolf
|--> accessories
|   |--> +shackles
|   |   //holds the cufs to be addet to the avatar

In order to change from human_avatar(nostrip) to werewolf_avatar(nostrip) i use chat commmand:
xy+werewolf
//And that works quite well. But, changing back, meaning REPLACING the folder shows some problems. Let me explain.

xy+human 
// that would not work because it wont get rid of the werewolf attachments

xy-werewolf 
// would also not work because of nostrip rule wich is important because of savety for RLV traps

I could add some dummy prims to the human folder that will over write the werewolf attachments. But then if i add shackles, gears, clothes, huds, i will run out of attachment points eventually.

The collar rlv menu offers to ADD, REMOVE and REPLACE a folder
So REPLACING the werewolf folder with the human folder work just perfect

And thats what i am working on. I try to add a new operator sign that makes use of this behavior. For that i would need a new folder prefix that indicates that this folder should replace any other folder. i am thinking of a (=) sign as it is indicating that  AVATAR is equal to FOLDER.

xy+shackles // adds the folder rlv/accessories/+shackles
xy-shackles // removes the folder rlv/accessories/+shackles

xy=human // would replace everithing and anithing with the rlv/body/=human(nostrip) folder

xy=werewolf // would replace everithing and anithing with the rlv/body/=werewolf(nostrip) folder

And as a last thought. It should not be posible to ADD a (=) folder as it would just screw up everithing. instead this command should yield a error message

xy+human // rlv/body/=human(nostrip) can not be addet like this try xy=human
xy-werewolf // rlv/body/=werewolf(nostrip) can only be replaced

I am currently working on that. And as soon as i have something runing i will post it here

Thanks for Reading.
