### ISSUE TITLE
Moire Collar: llDialog: message too long, must be less than 512 characters

### ISSUE THREAD

**Issue by pats33** [OpenCollar/opencollar#285]
since i did the updaqte 3.968 i have a problem getting in the page 4 of a folder it say  Moire Collar: llDialog: message too long, must be less than 512 characters like there a folder in the maine folder that cause trouble.the earlier version work perfectly

**Comment by WendyStarfall** [comment]
Needs further investigation if it is connected to #253 but getting there :dango:

**Comment by WendyStarfall** [comment]
The issue is not connected to #253 

Possible reasons are that the folders and subfolder names changed or increased in overall character count.

A solution would be to use shorter names for folders as well as subfolders and is also recommended because short names are easy to memorize and call via chat command.
