### ISSUE TITLE
OpenCollar 3.968 RLV Relay releases restrictions without permission.

### ISSUE THREAD

**Issue by fmtaylor** [OpenCollar/opencollar#289]
The RLV Relay in OpenCollar 3.968 (and other unknown previous versions) release restrictions after 60 seconds without being issued a command to do so.  To reproduce, issue a simple restriction such showminimap=n and then do nothing.  after 60 seconds the restriction is released.  

You may contact Fmagick Zymurgy inworld for additional information if necessary.

**Comment by WendyStarfall** [comment]
We haven't been able to reproduce it so far with the traps we use for testing.

Could we get a slurl for a place that hosts such a device, please?

**Comment by fmtaylor** [comment]
Sorry, I am AFK at the moment. 

The maze Relay test device is located in broo close to 35/57/801. It is
marked. 

On 13.07.2014 23:52, WendyStarfall wrote: 

> We haven't been able to reproduce it so far with the traps we use for testing. 
> 
> Could we get a slurl for a place that hosts such a device, please? 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/OpenCollar/OpenCollarUpdater/issues/289#issuecomment-48863322

**Comment by littlemousy** [comment]
I found the maze relay tester, and found the problem.  Its an issue with the garbage collection in the collar relay.  One of its checks is that the controlling device is within shout range, possibly a historic constraint, I don't know.  The device creating the restrictions appears to be 130m away from the tester device, so garbage collection is removing the restrictions because it thinks they are no longer relevant.

After removing this range check from the relay's garbage collection, I can no longer replicate the problem on this device.

I need to chat with Satomi (original author for this script) that it won't have any unforeseen repercussions before I commit the change.

Thanks for the report, Fmagick.

**Comment by SatomiAhn** [comment]
Hi. Shout range is a little less relevant than it used to be, thanks to (because of?) llRegionSayTo().
But one "little" detail remains: capturing devices often need to receive messages directly from the victim's viewer, i.e. : a regular agent chat message, limited to shout range!

I see this as a conceptual flaw in the relay protocol (such a protocol should not have relied on messages coming from different sources: it would have been better, more flexible and more resistant to technology upgrades, if the relay would work both ways, relaying messages from viewer to capturing devices). But the protocol is as it is.

So we are stuck between two relay implementation choices:
1 (safe one) - cleaning up restrictions starting from shout range, thus dropping sources as soon as correct working cannot be guaranteed anymore. In this case, mazes must adapt and make sure a restricting device is always within range.
2 (flexible one) - cleaning up restrictions only if the source is not in the region. This can lead to some devices not receiving viewer answers and potentially go awry.

**Comment by fmtaylor** [comment]
Of course you know I vote for the second choice, as it is simpler for me to implement.  All of the traps I have written use llregionsay or llregionsayto to do their communications, and if I was up to writing a relay, I would code it that way also.  But as you say, the spec is what it is.  I will work with whatever the final decision is.

**Comment by littlemousy** [comment]
Before we make a decision on this, would it be worth investigating other relays to see how they cope with the problem?  The Maze at Rolyat hands out a relay (Multi-Relay HUD - 1.03b4) when a wearer's relay fails the tests.  This relay seems to work without the same issues the collar's relay has.

I'd pick through it myself, but I have a feeling there are others that know it a little better then me :)

**Comment by SatomiAhn** [comment]
Multi-Relay and OpenCollar Relay are sort of cousins. It's possible I changed my mind between the two options at some time of the development of one of the branches (maybe another hint that it's hard to make one's mind on this issue!).

Concerning your maze, would it be scandalous that you force using your own relay, which would meet all your specifications?
I would not mind wearing a Maze HUD when visiting such a place (even less for your huge construct, in which we are likely to stay for a very long time, making the inconvenience of having to attach a ad hoc relay first, only a minor one).

Also if you can document your addition/changes to the protocol, maybe this could benefit to other maze makers (and maybe other RLV toy makers).

**Comment by littlemousy** [comment]
Wouldn't that cause problems for collar wearers with the relay locked on by their owner?

**Comment by SatomiAhn** [comment]
Then I suppose another channel would be used as not to interfer with already worn relays.

**Comment by fmtaylor** [comment]
Actually a copy of 1.03b4 coded to use a different channel would work, and compared to all the other options would be the simplest for me to code for.  The only real issue I see is that they would still have to have a standard relay on for the "native rlv" traps I did not write.  But that is not a real concern for me, it is a trivial problem.

**Comment by SatomiAhn** [comment]
You may want to use a more lightweight relay than this one though (especially if it's used only by the maze controller!)... but... this going outside the scope of this issue, sorry :).

**Comment by fmtaylor** [comment]
Well, when the issue is resolved, one way or the other, I will make whatever adjustments are necessary.. ;)

**Comment by fmtaylor** [comment]
On the subject at hand, shouldn't the ping-pong handshake be adequate to determine if there are stale sessions?

**Comment by SatomiAhn** [comment]
First I would remark that pinging every two minutes is not what I'd call an efficient usage of sim resources!

That said, a device answering a ping is definitely still there. But that does not mean the device takes into account the big distance. However we may consider it meaningful that the device bothered region-saying its reply instead of shouting it. Still, that does not rule out devices that would region-say for no reason, or just because the newer regionsayto is lag friendly. Grey area again !

In this cases, usage often becomes de facto standard. OC, as one of the major players, must act responsibly. It is the opportunity to remind you all of the existence of the Open Relay Group, where such questions can be debatted. Then I (or some other member) would document the most acceptable answer on the wiki.

**Comment by SatomiAhn** [comment]
Back to basics, I try to look into
- the canon RLVR spec by Marine Kelley: http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Relay/Specification
- and into Open Relay Group spec: http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Open_Relay_Group/ORG_Requirements

In MK: there is no mention of shout distance, and that a relay would unilaterally release restrictions when out of range (no explicit ban although!). So there is no "grey area" per se. The gray area appears when the reference implementation started to try coping with some bugged grabbers that would let their target go out of range without releasing their relays.

In ORG: it is stated that the relay is expected to end the session as soon as a restricting device is unreachable. It is also said, that in a normal setting, beyond shout distance, the device is unreachable. This stipulation formalizes what many implementations were already doing at that time.

To sum it up: not releasing at shout distance would satisfy MK but would violate ORG. However, as this is not a very fundamental point, I think it would be reasonable to update both OC and ORG spec to consider that default range is the whole region.

What could go wrong with such a change:
- buggy devices that forget to release could become an issue again (until we escape the region... when it is possible!). This was the initial motivation for automatic release, but nobody should be expected to try coping with every possible bug from other scripters anyway.
- more embarrassing possibility: if there exists some RLV device that relies on this automatic release when escaping shout distance. I am not aware that such a device exists and I think it is unlikely, as this would very unrealistic to expect that all relays check range (not mandatory according to MK).
- as to devices that would try using @getXXX=chan commands beyond shout range: nothing changes for them if they were already preventing the victim from going too far away. In the other case the device falls back into one of the first two bullets (either they were oblivious of the range issue -> first bullet, or they believed that somebody still restrained is necessarily still in shout range -> 2nd bullet).

According to the above, I see no very compelling argument in favor of shout-range checks, but I will send a few IMs to ORG members and see what they think about it.

If the spec remains as it is (and I believe OC should keep sticking to ORG spec as close as possible!), it is still conceivable to add some optional commands for changing range.
In every case, the incompatilibity of this maze with existing range-checking relays will remain.
