### ISSUE TITLE
Confusing message by LeashTo button when no avatars are near

### ISSUE THREAD

**Issue by TucoSolo** [OpenCollar/opencollar#29]
**What is your Second Life name?**
Tuco Solo

**What steps will reproduce the problem?**
As a primary owner of your own collar, go to a quiet place. Enter the Leash menu and select LeashTo.

**What is the expected output?**
Something like "Unable to find any nearby avatar targets."

**What do you see instead?**
"Unable to find any nearby targets."

**What version of the collar (or other item) are you using?**
3.931

**Please provide any additional information below.**
I don't use the leash option that much. As a user/tester I expected this option LeashTo to be valid for non avatars, like a leash post, too. By adding just the word "avatar" in the message this may take some confusement away.

**Comment by WendyStarfall** [comment]
LeashTo is what it is, for this to make sense we would have to take a much closer look at the whole of it, make sure that the "Unable to find any nearby targets." isn't re-used for post and follow and ask ourselves to eventually remove post as a command and menu function if we wanted LeashTo to deal with both cases. Further that leads to thoughts about integrating the Real Leash into the standard leash system and like most things in the current architecture would require much more time to change than it will be to re-write the leash for 4.0.0 from scratch.

The vast majority already knows how it works, especially those who use menus frequently. This had never been an issue before. If we now change stuff around that frequent menu-users are familiar with, we end up asking them to re-learn 3.9 systems just to shortly after totally re-learn for 4.0.0.

I'd still like to thank you for bringing this up because it's one more thing we are reminded to handle differently in the new architecture. If we get a pull request for a perfectly working leash menu overhaul + real leash integration that is rock solid, I wouldn't turn it down but I just invested over two hours into this without useable/stable result so for me personally the leash topic is closed.
