### ISSUE TITLE
version 3.971 - scripts errors in rlvmain that kills rlv

### ISSUE THREAD

**Issue by BethanyLynn** [OpenCollar/opencollar#299]
Getting script error for rlvmain that requires me to relog to be able to remove the UNLOCKED collar and do a script reset.

**Comment by WendyStarfall** [comment]
We spoke about this on the forum and a solution in form of a whole now item had been provided.

A day later we spoke about in-world and learned that several outdated (by years) plugins were moved from the old device into the new device and also that scripts were re-compiled (likely not in mono).

None of this is mentioned here in the bug report; friendly and dedicated help had been provided.

**Comment by BethanyLynn** [comment]
you insufferable twit
you lack what it takes to solve problems so you resort to accusing others of your own lack of intelligence

Date: Fri, 1 Aug 2014 06:29:52 -0700

**Comment by WendyStarfall** [comment]
Transaction entry of the brand new ring, I created for you and sent to you:

| 2014-07-24 23:56:35 | ab35ba31 | NewMe Allardyce | Give Inventory |
| --- | --- | --- | --- |

Chatlog of the support query, without your replies to value your privacy:

> [2014/07/26 23:27] Wendy Starfall: Hi Bethany, I will need to know a few things so I can help you better. What viewer are you using, name and version number? Are you re-compiling the scripts the, old LSL way in an attempt to save memory? How many owners and sec owners do you have stored in your collar? Were you grabbed by an object during time of collision, like a cage or trap or bondage bed? Did you add anything else to the Ring, like a cuffs plugin or similar?
> 
> [2014/07/27 06:05] Wendy Starfall: Hi, viewer is good, recompile could become a problem if you don't compile in Mono; one or more of these plugins will be causing the issue
> 
> [2014/07/27 06:05] Wendy Starfall: I'm not familiar with the OCNameOverider_1.0b
> 
> [2014/07/27 06:06] Wendy Starfall: Cage Home is at version 0.3, which would be 3.9 API compatible and can be found here https://github.com/OpenCollar/OpenCollarUpdater/blob/main/SPARE_PARTS/OpenCollar%20-%20cagehome.lsl
> 
> [2014/07/27 06:07] Wendy Starfall: real leash you will no longer need, there is now a tickbox in the normal leash menu called “Strict” which does the part
> 
> [2014/07/27 06:08] Wendy Starfall: OpenCuffs-_slave will break things too
> 
> [2014/07/27 06:09] Wendy Starfall: keyholder is maintained by the original author, you will find an up to date one here https://marketplace.secondlife.com/p/Keyholder-Plugin-for-OpenCollar/5852091
> 
> [2014/07/27 06:11] Wendy Starfall: each of these plugins you moved, for the exceptions of the name overrider which I'm not familiar with, are over three years old and three api version behind – that will break things
> 
> [2014/07/27 06:13] Wendy Starfall: the OpenCuffs slave was part of the first 8-set cuffs, it will try to tell this ring “You are part of a set of cuffs.”
> 
> [2014/07/27 06:14] Wendy Starfall: cage home adds a feature that teleports you to a predefined location as soon as your owner logs on

Please note the dates.

Since it is visible here that I tried with the best of my ability to help you but you continued posting this query everywhere you apparently felt was "OC official", I have to understand that you don't actually have a problem but your deal is to post a false query about colliding scripts.

You also wrote on the forum that "this was not worth your effort". Pointed out how you would rig the version card to no further get notifications and other information that isn't congruent with your claim to lack the advanced technical ability of being able to manipulate scripts or to compile LSL vs Mono.

What about the effort of the unpaid people who continuously work on this device to improve it?

What about my effort to not only provide dedicated support but also make an all new thing for you?

Why, for the love of God, do you not include the details of the support you already received if you feel the need to create new issues and posts over and over but continue to spam a headline that leads people into believing the update release is malfunctioning?

There have already been over ten thousand updaters distributed, installed and run just fine. Your public derailing here and on the forum is proof enough to demonstrate where you are coming from.

However, likely you feel entitled a professional response as well:

**Comment by BethanyLynn** [comment]
laughs hysterically at such foolishness.  Fully expected though, given the foolishness I encountered in our previous interaction.

Date: Fri, 1 Aug 2014 15:25:13 -0700

**Comment by XenHat** [comment]
If you're replying from e-mail, please delete the reply quotes. It looks horrendous on Github.
Also, this is a **BUG** tracker, not a bitching contest nor a "let's teach basic manipulations" Class. Insulting people who take time to work on this project by calling them "twits" and "lacking intelligence" while it appears that you clearly did something wrong is pointless.
![be-nice-or-fuck-off-new](https://cloud.githubusercontent.com/assets/980408/3788336/4401e048-1a5f-11e4-9783-886dce530a81.png)
