### ISSUE TITLE
No Touch menu on the Collar after updating it to the beta version

### ISSUE THREAD

**Issue by MaxieClaveau** [OpenCollar/opencollar#3]
I tried updating a collar by wearing one, the tried again on another collar dropping it first. Neither one has a "touch" menu. The only way to get the menu is chat command. Also, can right click, and there is no "touch" option in the pie menu. I also tried resetting the scripts on the first collar.

**Comment by WendyStarfall** [comment]
That sounds like an RLV kink maybe? What viewer are you using and what version, also, have you been wearing any other gear or had any RLV restrictions set on the collar prior to updating?

PS: Thanks for the message in-world, the script error messages about "not finding stuff" are asset lag, I have only been able to work around this by moving the sequence of items in the updater bundles around. I hope the asset lag isn't connected to project sunshine because I have it constantly when editing contents inside objects and this "small bugs" quadruple the amount of time for me some stuff. Linden Research, you read that!? Fix it! Durr... =)

**Comment by MaxieClaveau** [comment]
No, I don't have any kinks on it. Both collars had a touch menu BEFORE!! I updated it to the beta.
I've not yet updated my Firefox viewer to the latest, but, it's only one version behind.
Thanks. \* hugz*

**Comment by WendyStarfall** [comment]
Are you sure this isn't an issue caused by alpha channels on the hairstyle you were wearing at the time? I get the menu up without any problem on touch.

**Comment by MaxieClaveau** [comment]
Even my Master couldn't  get a menu by touch when we could before the update.

**Comment by WendyStarfall** [comment]
Ack! Sorry for that, it was because "touch" wasn't in by default. That was silly of me to put as optional feature. Anyway hotfix is out for main channel and beta has been updated as well. Your issue will be fixed at 3.916 or 3.920, red or blue will be good!

**Comment by MaxieClaveau** [comment]
THanks ((wendy)) :
