### ISSUE TITLE
Update Leash Effects

### ISSUE THREAD

**Issue by NoriMouse** [OpenCollar/opencollar#301]
Now that the new Ribbon Particle effects are implemented and accessible in SL, it could be a good idea to swap out the outdated, disconnected particles with a continuous particle stream. It's as easy as adding PSYS_PART_RIBBON_MASK to the list of particle system flags on line 205 in the script 'OpenCollar - leashParticle'. 

Preliminary discussions regarding the implementation of ribbon leashes into OpenCollar brought up the point that a singular ribbon would look "flat", as ribbon particles do not always face one's camera; however, multiple workarounds may be used to add depth to the leash including the addition of a second particle emitter, rotated by 90 degrees, or by adding an llSetLinkPrimitiveParamsFast(emitter, [PRIM_OMEGA]) call for the leash particle emitter link to make it constantly rotate.

An example of the current leash particles; note the disconnected appearance
![chain old](https://cloud.githubusercontent.com/assets/4810563/3789743/35044a5e-1abe-11e4-937a-22ba59a948f8.png)

An example using a ribbon particle replacement. 
The UUID for a chain ribbon particle texture is 06ffe23a-4819-12b4-dd9b-b4a845d16a57
The UUID for a rope ribbon particle texture is c63b0ed0-948a-6ec5-8119-a66aef9ab5b9
![chainnew](https://cloud.githubusercontent.com/assets/4810563/3789742/35018af8-1abe-11e4-90d4-482bf720fa59.png)

**Comment by SilkieSabra** [comment]
Would the workaround you propose for the flat appearance add to the script load or particle lag?

**Comment by XenHat** [comment]
As far as I could test (with overkill settings, over the course of several
months), the ribbon particle is virtually lag-less (on the server as well, since it's completely viewer-side. Tech talk about it on the LL JIRA points that the server LSL flag is a dummy to prevent compiling error). I don't think that a single particle flag would increase the load time by a significant amount
either.

**Comment by WendyStarfall** [comment]
I've been watching experiments with the ribbon particles and haven't been convinced of their use for chains or round rope. That was a longer while ago though. However, they would be absolutely awesome for silk or cloth leashes and I'd swap my rusty chain for a perfumed silk band anytime. :princess:

This will get mixed reception, some will like it, others will moan and groan, especially if we just dropped oldschool particles and worked in a rotating or dual emitter ribbon leash. My belly tells me, this will be celebrated as option in the Particle sub menu but as a replacement would likely cause a racket.

I will try to get Kyrah Abattoir to join this discussion, she could give extremely valuable input on this.

**Comment by kyrahabattoir** [comment]
The main issue is that ribbon particles make it even harder to give the illusion that the particles are NOT flowing, but i would love to be proven wrong. So far according to my tests, ribbons look terrible as chains.

They may do a decent job for nylon cables, lasers and other objects with no patterns tho.

**Comment by XenHat** [comment]
I haven't actually tried it, but what if we gave the particle a very low
velocity or a long life time? wouldn't that reduce the "flowing" issue?

**Comment by kyrahabattoir** [comment]
Then you get an equally long "stretchy lag" in the particle strip. and unlike regular particle chains, these deform when they get stretched.

**Comment by WendyStarfall** [comment]
I'd like to see it as an option, we would need a button for it and also a way to define it in current defaultsettings.

Something for old-school:
User_leashParticle=Texture~particle~chain

Something for ribbinz:
User_leashParticle=Texture~ribbon~silk

:tada: How the string formatting is done is best left to the settings nerds! :tada:

A spot for the option we have free in our Particle submenu. In the same motion the noLeash button should be axed cause redundant since we have a fancy FollowTarget right in the default Leash menu.

The menu design specification queen bee elaborates:

:honeybee: Leash -> Particle -> Texture

| Default | Chain | Rope |
| :-: | :-: | :-: |
| Dots | Silk | BACK |

A challenger appears!

:hatched_chick: "Guys!"
:hatched_chick: "This is silly, we rather had an option to choose if ribbon or standard particle!"
:hatched_chick: "If we do it like queen bee says, only designers or scripters can hardwire the particle type!"

:honeybee: **bumbles...**

The rebellious chick elaborates:

:hatched_chick: Leash -> Particle

| Texture | Density | Gravity |
| :-: | :-: | :-: |
| Color | Size | Life |
| [ ] Glow | [ ] Ribbon | BACK |

:person_frowning: "Err.. what about ResetDefault?"
:honeybee: **bumbles...**
:person_frowning: "You would have to reset to default for density, gravity, size and life each individually.."
:hatched_chick: "We need a more robust factory defaults system anyway."
:hatched_chick: "Running settings will always be returned anyway without reference to the notecard."
:mouse: "If a designer setting is present, it will always be returned in preference to a user setting.  In this respect, it is returning a default setting, but does not allow the user to change those defaults without compromising the design of the collar."
:honeybee: **bumbles...**
:person_frowning: "Works fine on my brain implant! Pffff!"
:honeybee: **bumbles...**
:hatched_chick: "Maybe not the right place and time to discuss settings."
:hatched_chick: "Still, we should.."
:frog: "Ribbit!"
:frog: "Ribbit!"
:frog: "Ribbit!"
:hatched_chick: "Seriously? Be quiet.."
:hatched_chick: "What I was about to say.. oh yeah, we should have an option to let the user decide: do I want an oldie particle or do I want a ribbon."
:hatched_chick: "Nuff said."

Now that all the animals have spoken, I'm even more confused than before. Maybe we should ignore what the menu looks like and just make a switch for users to choose their particle type?

:person_frowning: "I'm not an animal...."

**Comment by XenHat** [comment]
How about letting the user decide if they want to respect the design preferences or not, and if not, what particle type?

EDIT: With a warning of sorts to be sure they're aware of what they're going to break

**Comment by kyrahabattoir** [comment]
What's wrong with designers and scripters doing their job tho? You expect the average user to tweak for an hour their particle/ribbon aspect?

**Comment by SatomiAhn** [comment]
The collar should expose all possible options to the designer through the design settings notecard.
But there is no need to flood the casual menu user with millions of buttons: a few presets (including OC default and designer preset), and a few basic settings (which?) should be enough.

**Comment by WendyStarfall** [comment]
:honeybee: **agrees...**

That's right, I'd like to see the particle options, per designers configuration and because I know from user requests, a color dialog. Nothing more, particle density, size, life, glow and what not I, personally, don't think should be expected of users to configure but the designers effort to ship in an esthetic manner.

| Default | Chain | Rope |
| :-: | :-: | :-: |
| Silk | Color | BACK |

Now, let's imagine a designer adds 4 more options, where Default is their own designs specific default.

| Default | Chain | Rope |
| :-: | :-: | :-: |
| Silk | Rubber | Daisies |
| Snowflakes | Hearts | BACK |

Ribbon particle or not, is up to the designer. They might use it for Rubber but not for Daisies.

:hatched_chick: "Guys.. guys! This is silly! Users in OC always can set everything, it's one of it's major appeal.. wait, what are you doing with that knife? Wendy?"

:poultry_leg: " ... "

**Comment by WendyStarfall** [comment]
superseded by #341
