### ISSUE TITLE
Leash Holder uses old style UPMENU

### ISSUE THREAD

**Issue by TucoSolo** [OpenCollar/opencollar#31]
**What is your Second Life name?**
Tuco Solo

**What steps will reproduce the problem?**
Wear the Leash Holder and click it. Select one of the buttons in the main menu.

**What is the expected output?**
A submenu with a fancy "⏏" as up-button.

**What do you see instead?**
The old "^" up-button.

**What version of the collar (or other item) are you using?**
The Leash Holder in collar 3.931

**Please provide any additional information below.**
- Version numbers of OC scripts in the leash holder:
  dialog 3.400
  handle 3.422
  update (no version in script name)
- Regarding the update script: it tries to contact a web address at data.mycollar.org. Is this still actual? It also relies on the description of the object, for retrieving name and version. I also believe this is outdated? Normal operation seems unaffected, btw.

**Comment by WendyStarfall** [comment]
that url is still current because we still use AppEngine for the vending network and the updater distribution is part of that; on the leash holder, I don't think I'm going to bother fixing it unless someone sends me a fix, the Velveteen Scribe holders I put in the contents to get them some more into circulation. he did a nice job on them and they were sadly overseen during the years by too many users. a new leash holder without the scriptie baggage added I have ready to drop into whatever new version to come but again.. those weren't hyped enough when they were fresh and they well deserved a little revival phase =)
