### ISSUE TITLE
TP command overrides TP restrictions

### ISSUE THREAD

**Issue by masterofsorts** [OpenCollar/opencollar#316]
The prefix tp commands override all TP restrictions. If someone is in a cell/cage and has a public access collar. Anyone within chat range can tp them to any preset destination i.e temple. 

There does not appear to be any auth checking

**Comment by SatomiAhn** [comment]
And another case of the old dilemma of integrated relays, considering that:
- collar + integrated "multi"-relay attempt to emulate several RLV objects from a single prim
- RLV TP restrictions do not block forced  TPs from the same object

Should we
- 1 - just ignore/accept the fact that some restrictions (such as TPs) can be circumvented using other collar plugins (or other relay controllers, by the way)?
- 2 - detect and block force TPs when TP restrictions are active (problem: such ad hoc tests could be added for many RLV restrictions, existing or to be added in the future, presenting similar issues) ?
- 3 - move the relay to its separate prim (but then remains the problem that it is a "multi" relay, and some controller might still send a TP order that would just work despite any TP restrictions from another controller)?
- 4 - move RLV-restriction-issuing scripts to a _set_ of separate prims (one 'core' per restricting object and RLV plugin, as it is done in many relay HUDs)? ... as you can see, in the perspective of collar integration, this would be a huge hassle

As you can see there is no ideal answer. Maybe we should go for solution 2, no matter how inelegant it is, because this one would work and can realistically be done. Then we will need to keep an open eye for newer RLV commands and restrictions that may interact in undesirable ways.

In order to factor the effort efficiently, I think this should take place in rlvmain. Then this would block TP commands coming from any source (rlvrelay or rlvtp plugin or others... ). Maybe rlvmain could send a LM back to plugins saying whether a RLV command was transmitted to the viewer or not, thus allowing rlvtp to notify the menu user when something does not work.

---

Some additional comments below on this topic and related ones (that will not help solving our issue in the immediate future):

We can remark that problem we are discussing now exists for TP restrictions but not clothing restrictions (clothing restrictions also block clothing commands coming from the object issuing the restriction). This lack of consistency in the RLV API makes it hard to script multi-plugin toys (or multi-sources relays) as you can never know what result to expect unless you have a very precise knowledge of the specification.

I do not know if one way is better than the other. In many cases it can be useful not having to lift your own restrictions for only a brief instant just to send a command that would have been blocked. But, as we saw, this type of behavior makes it hard for several plugins to cohabit within a single prim.

If I was doing the deciding, I believe would go for the following: make it so that a restriction does not block commands issued from the same session (~ object), but allow creating several virtual sessions from a single prim (having thus the RLV handle each virtual session as a separate object). This would not be much to add to the viewer (I had a nearly working implementation based on RLVa).

I know that the API does not move much of late, and that my proposal would be like a Copernican revolution in this context. However I'd like to point the fact that no loss of backward compatibility is necessary.

**Comment by littlemousy** [comment]
Thanks Satiomi.

I agree that solution 2 would be the easiest way to go.  rlvmain already has all of the information it needs to make this decision. I'll put together a patch based on this.

A link message back would be nice too, I'll try to get that in as well.

**Comment by SatomiAhn** [comment]
If you add the link message back, I think it would be important that the link message be generic enough to work with other similar cases.

Ideally it should include:
- the client's name: controller UUID if that was coming from the relay, plugin name, if that was coming from another plugin (little problem: rlvmain does not have this information... but I think I remember there was recently a discussion to use the blank UUID of RLV_CMD messages to that purpose? couldn't we add this in the process?)
- the command that was refused
- an instance identifier... which could also be added as a field to RLV_CMD (ok, another thing that does not exist yet!)
- a boolean whether the command was accepted or not
- a string for the reason of refusal

(note the 4 first fields exactly correspond to the 4 fields of rlv relay acknowledgement messages :-) )

Fields we don't have the means to fill yet could be left blank until further developments.
