### ISSUE TITLE
RLVa detection and version notification

### ISSUE THREAD

**Issue by SumiPerl** [OpenCollar/opencollar#413]
Provide RLVa version to scripts that can provide extended capability when it is available.

Background:
@versionnew was introduced in 2010 and provides additional versioning information that the current @versionnum (introduced late 2009) in rlvmain wasn't able to gather.  RLVa uses @versionnew to relay the version of RLVa that the viewer has loaded, that isn't currently available to any of our scripts.

Proposal:
Replace @versionnum with @versionnew, and introduce a new linkmessage:
RLV_VERSION 6003 (current)
RLVA_VERSION 6004 (add)

Reasoning:
RLVa provides some extended capabilities that we aren't currently able to use since we don't know if we're dealing with RLV, or RLVa.  With this, we would be able to take advantage of features such as multiple folder matching on rlvfolder searches intelligently, knowing that RLVa is present, and deal with it smartly.

Complication:
Unfortunately @versionnew requires some string manipulation to decipher the versioning correctly, whereas @versionnum was a single string or numerics that determined the RLV version

**Comment by SatomiAhn** [comment]
Back then when I made it so rlvfolders use @versionnum (instead of @version), @versionnew had already existed for a while.

I am pretty sure there was a reason why I chose using the former... although I do not remember which. Maybe easier parsing. Maybe the fear that some day a @versionevennewer became needed. @versionnum's format looks a bit more time proof.

Today (and even back then) I have no strong opinion on the topic. I just wanted to bring this piece of history to you while you are making choices.
