### ISSUE TITLE
from 3.980: restore "wear/replace" button in #RLV folders

### ISSUE THREAD

**Issue by DariaLinette** [OpenCollar/opencollar#441]
I have several outfits in #RLV folders having multiple configurations, each stored in an appropriate subfolder.
But since 3.980 update, the "replace" button has gone. Only "add" is left. So I can no longer use those outfits properly from my collar.
If possible, I'd like the "replace/wear" function to be back in menus on next update.

**Comment by SatomiAhn** [comment]
Some folders (containing one item of clothing) are meant to be added (and replacing would make a mess), some others (containing a full outfit) are the opposite way.
As it is a good idea not to display buttons that would make such a mess, I don't think that both "add" and "replace" should be shown in the same menu if that can be avoided. Instead, I believe the collar really needs to be told what to do on what folder.

"Easy" solution (not flexible enough): RLV and RLVa viewers make it possible to make the default action "add" instead of "replace" by prefixing a "+" to the folder name. So having the collar only proposing "replace" would achieve the goal. Except that this "+" everywhere really looks ugly...
(ideally there would be a way to configure the viewer so that the "add" mark would be a suffix... or even to make "add" the default, and have a mark for replacing instead)

Other solution (preferred, despite heavier scripting required): instead of adding a visible mark in the folder name, add some invisible subfolder specifying what the default action should be.
Invisible subfolders are subfolders of #RLV prefixed by a "." (not listed when browsing their parent folder with @getinv/@getinvworn). Despite not being listed, they can still be queryied.
So, say for instance a folder contains a subfolder ".default_action", containing another subfolder called "add",
(subtree:
 #RLV
  |- my_outfit
  |  |-.default_action
  |  |  |-add
)
then the script could query the contents of ".default_action" folder (@getinv:#RLV/my_outfit/.default_action=1234) and thus know that the default action should be "add".

Actually I would not use ".default_action" as a name for the hidden folder, but something more generic instead, such as ".metadata", so other settings could be added in the future for this folder.
