### ISSUE TITLE
InterfaceChannel  and attachments communication.

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#456]
for communications with attachments, like AO HUD, cuffs, e.t.c.
some scripts contains    llWhisper(g_iInterfaceChannel, g_sMessage);

why not use   llRegionSayTo(g_kWearer, g_iInterfaceChannel, g_sMessage);   ?
it allows to send a message to only own attaches, others avatars standing near will not recieve this message.

**Comment by XenHat** [comment]
If I had to guess, i'd say it's legacy code from before this function existed. I also am in favor of using the `llRegionSay*` function set as they have no forced delay between messages.

**Comment by ghost** [comment]
I am in favor of using the llRegionSay\* too.

What others says?

**Comment by littlemousy** [comment]
I vote for llRegionSayTo.  No reason to trouble nearby avatars' attachments with messages for the wearer if we don't have to.  Go for it.  

The attachments won't even know we're using llRegionSayTo instead of a whisper.  They'll hear it just the same.

**Comment by ghost** [comment]
Yes, yes, a little more vote, and I will do the patch :)

**Comment by XenHat** [comment]
\0/

**Comment by ghost** [comment]
#457

**Comment by WendyStarfall** [comment]
Hey guys!

llRegionSayTo was introduced in 2011 with [server patch 11.04.26.227686](http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/11#11.04.26.227686). We had the llWhisper because at the time it was preferable (no need to have used llRegionSay for attachments but the shortest possible range which was even llWhisper). We are safe to use llRegionSayTo, it's now the best method for this.

Thanks for spotting this, Romka, this is a good change! :cat: -> :icecream:

**Comment by littlemousy** [comment]
While we're on the subject of chat and notifications...

There's a lot of Notify(g_kWearer,....) going on all over the collar.  Why do we route wearer comms through Notify when all it does is pass it to llOwnerSay when it gets there?

It beats me.  I've just merrily carried on following what was there without really thinking about it, but on reflection, it seems a little inefficient.

**Comment by ghost** [comment]
Oh, you're right!
I started working on this
