### ISSUE TITLE
Enhancement: Disable third party apps/scripts

### ISSUE THREAD

**Issue by natalja92** [OpenCollar/opencollar#480]
i would like to get an enhancement to disable third party scripts/apps  via collar itself that would help debugging.The collar could check the prefix of a script name, and the creator of a script itself. 

after a relog all scripts that are not from the OpenCollar Team, should be blacklisted, disabled.

**Comment by littlemousy** [comment]
Anyone can edit an OpenCollar script, the creator name wouldn't change, that can't work as a test.  Anyone can rename a script to start "OpenCollar - ", that can't work as a test.

I have a few custom scripts in my collar that I wrote myself, and others I bought from third parties.  If the OC scripts disabled them at every login, I would be very upset.  I imagine a lot of third parties that write commercial scripts they sell to OC users would be upset with the disruption to their busninesses too.

**Comment by KarinKorpov** [comment]
But LittleMousy, may a shop also sell collars with only a update possibility from the shop? I thought that OpenCollar open was and the update always possible was from opencollar or even the edit possibility must have. Only i am not very sure, that's why i now here also ask

**Comment by littlemousy** [comment]
I'm not sure I understand the question, or it's relevance to the OP's question, but I'm happy to answer it.  I'm no legal expert, and don't officially represent OC, but my reading of the license is this.

There is nothing in the OC license that says you have to leave the update function intact, or compatible with the regular OC updater.  A vendor selling an OC scripted device could rewrite the update function to work only with their own updaters, that is the nature of open software.  If they based their update on the OpenCollar updater, they would have to give people access to the code by leaving any scripts based on OC code modifiable.

The license does say that the scripts, or anything based on them must be left open and editable, and the item containing them must also be modifiable.  This means even if a vendor were to disable the update function, you could still manually reload standard OC scripts from an updater or another collar.

**Comment by WendyStarfall** [comment]
@natalja92 :

For debugging I just use a fresh, standard collar without anything else installed and if I was going to check if my custom plugin is causing a problem, add it to the "pure" OpenCollar and observe any change. Then add the next and the next and so on. @SumiPerl wrote a drop'n'debug script once, a feature to pause all scripts without "oc_" (for 4.0) prefix could be added to such a script too.

@KarinKorpov :

Other parties are free to make their own channels of course so to have more control over when they want their users to receive the update notifications.

I insisted that this was made possible in a very simple way already for 3.9 and still is even more so for 4.0 where you can specify your own dedicated updater as well as allow an override to "vanilla" OpenCollar.

If another party chooses to fully shut off OpenCollar updates it is likely to their disadvantage though because when they might lose interest providing updates eventually, their users would still be able to keep their devices fully functional if scripts had to be adjusted to continue working well in harmony with viewer, server and rlv.

It is illogical to make things difficult and tricky for the users if it could be simple without any change in the first place. It is unwise to disable updates from upstream because it makes an item less future proof.
