### ISSUE TITLE
Removing second owner works not correctly

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollar/opencollar#493]
The option - Sec Owner works not correct

It says it removes from list when you removing do, but in exceptions stays the second owner
After a relog is the name also back when you do the option "List Owners"

I have it seen in version 3.992, i don't know or this correct work already in 3.993 version
Perhaps is a check needed. 

Regards, Karin

**Comment by WendyStarfall** [comment]
Thanks for spotting that, I've been able to reproduce the problem on 3.993 as well.

**Comment by WendyStarfall** [comment]
Okay, I've pushed a bandaid fix you can use for now if you compile auth from the main branch source.

The problem is our settings string for secondary owner, which is sometimes secowner and sometimes secowners unlike any other auth settings string that uses singular form.

Mouse will need to look at this, the block with adding the extra "s" I picked up from one of her earlier merges already a while ago, so credit to mousy for that one.

**Comment by WendyStarfall** [comment]
Okay, I'm home again and can give it another shot.
