### ISSUE TITLE
Defaultseting Label dosn't get set

### ISSUE THREAD

**Issue by steampilot** [OpenCollar/opencollar#494]
# The Hardwired Label dos not get set

While everithng else works like a charm, setting the label text in the DefaultSettings dos not work.
Here are my settings.

```
#---My Settings---#
User_label=Text~sub
User_Global=trace~1~prefix~sub
User_rlvundress=smartstrip~1
User_rlvmain=on~1
User_auth=owner~16d72d0d-bdef-405b-b1c7-dd0ccbdbeb61,Miss Cindy,fb85693c-7acd-4d32-9734-ff394689a5d4,Sir Jérôme~openaccess~1
User_titler=title~Owned By Miss Cindy & Sir Jérôme - submenu~height~0.900000~on~1~auth~500
User_subspy=trace~on~radar~on~listen~on~minutes~300~meters~18
```

**Comment by WendyStarfall** [comment]
We kind of did that on purpose because if someone wanted a permanent label, there is no real use for a plugin that changes the label. At the same time, only primary Owners can change labels, the wearer or other auth levels cannot.

An even better solution for permanent labels would be to create a nice texture for the writing as dynamic labels are very artistically limited.

> 64KB + multiple boxes/cylinders/8-face planes
> vs
> 0KB + 1 prim/1-face plane
> 
> ![some label](https://cloud.githubusercontent.com/assets/1100007/5189663/f46b87e2-74df-11e4-9663-c9b081214c38.png)
> ![some label2](https://cloud.githubusercontent.com/assets/1100007/5189784/ecb839b8-74e0-11e4-9e6a-c1cb91eb2d00.png)
> ![some label3](https://cloud.githubusercontent.com/assets/1100007/5189788/f179999c-74e0-11e4-9f98-9f76799ce621.png)

For a label texture I recommend a 24-bit TGA with appropriate resolution, no larger than i.e. 128x64.

It depends on others opinions as well but personally, I would like to see a method to apply labels for 4.0 systems. The label element can be a single model with three faces fitting for preset resolution and artists get an opportunity to create attractive addons or custom work that doesn't escalate in days of work for each request. Everyone can make their own personalized label or even hire someone to do it for them.

**Comment by SilkieSabra** [comment]
a label face where you can control-drag  or apply your own texture, thumbs up to that!

**Comment by steampilot** [comment]
## Dont mistake the Default settings for Permanent settngs.

All i am asking is that the Default setings work as they are described in the documentation.
As such i might say we should label this issue as bug.
I would give my collar with the  default settings of  [prefix, title, label] to "sub" so then i give it away and install it with this 3 lines of code

```
subtitle owned by jerome
sublabeltext cindy
subprefix cindy
```

the main reason is that i am not happy with the name initials as default. like cr for cindy resident. It happend that i have subs who have numbers as names like 17012501 resident.

**Comment by WendyStarfall** [comment]
Then it should load properly if you put `User_label=text~sub` and they put it on after receiving it.
