### ISSUE TITLE
[AddOn] Timer

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollar/opencollar#496]
I am not sure of this issue but i can remember in the past, was this:

As wearer, also as owner, when someone use the timer option could i never more use the collar till the moment that the timer running out did. 
On that moment had the wearer, what also an owner was, no access more.

Now at this moment, can i use the timer option.. very well till there.. everything works also till this:
As wearer and as owner have i access to my collar.

Is this with a thought done or as a bug?

btw, i am a wearer and the first owner of my collar
What i mean to say, when somebody else also a timer option use have i also access to the collar. 

I think honestly that better is, when the timer runs, also i as wearer no access more have to the collar.

Regards,
Karin

**Comment by WendyStarfall** [comment]
The authorization stuff in timer didn't change, what you describe is a "wearer lockout".

The wearer can lock themselves out of the system, except for triggering poses or whatever else gets exempt during this event. An unowned wearer would be locked out as well even though in that role they otherwise are equal to primary owner. If a wearer is added to the primary owner list, this will fail.

What you might want to try was to not to add yourself to the primary owner list. If ownership is desired, add them as secondary owners. Primary owner and "wearer owner" combined is like full root access.
