### ISSUE TITLE
Real Leash restrictions stay enabled when leash-holder goes offline

### ISSUE THREAD

**Issue by RayZopf** [OpenCollar/opencollar#50]
When Real Leash addon is enabled and sub is leashed, restrictions apply.
Those restricions still apply when leash holder logs off. Bad thing when owner/leash holder forgets to unleash before leaving. Need to check if wearer is leashed to post/object or person

**Comment by WendyStarfall** [comment]
EDIT: I changed my mind on this one. It's not really a bug though it may be for some users "unexpected behavior" and kind of annoying. For now we can put this as a known caveat in the system but since we are doing the leash from scratch for 4.0 I'm not sure how much we benefit from the experience now to wrestle a more organic behavior into our current leash and especially into an optional plugin for the current system.

We need to consider a lot of variables. From a leash holder who just crashed and logs back right away, cases where the leashed person actually is satisfied with the restrictions intact because they had not been "formally" unleashed or the fact that leashing is such a classic element in the kind of interaction that it may well be expected of a leash holder to unleash properly before bouncing.
