### ISSUE TITLE
tpto: commands no longer accepted as a result of previous push

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#522]
Back in December there was a change (https://github.com/OpenCollar/OpenCollarUpdater/commit/a83d2e6e1e82c117a3972942354e01103ce80fc8) that removed the ability for external objects (such as huds) to send teleport commands (@tptp:'coordinates'=force) to the collar. I do not know how to find the issue linked to this change so I am not sure why the previous form is problematic, but the current form breaks my hud and offers no alternative method for performing the same action.

If someone could explain what the issue with the previous version was, then I could propose a new change allowing this functionality to be supported without producing errors in obsolete huds.

**Comment by WendyStarfall** [comment]
This message, `llMessageLinked(LINK_SET, RLV_CMD, "tpt"+sCmd, kID);` was commented so other parties could adjust it if what they wanted was to receive tpto commands on the interface channel while we still prevent ugly errors in obsolete Owner HUDs with `llSubStringIndex(sCmd,"o:") == 0` and the empty function in place. That's how the system is intended to work since August '13 bookmarks release.

Bookmarks was never shipped with e7d92c08ea3cae53995d2ff0608c620aad66c051 merged in, where you moved the commentary slashes.

The functionality to send users to arbitrary sites with raw tpto coordinate rlv commands is not something we want to support. Surely users on public access don't expect being sent to remote simulators out of the blue or whacked into a wall unless they deliberately make the necessary changes on their own initiative.

RLV relays with popular "auto" vs. "ask" modes could be used to make it work to everyone's preference.

**Comment by ml132** [comment]
Perhaps we could support teleports only from people specifically on the access list (owners, sec owners, temp owners)? It's not really a big deal either way though, this could also be addressed by having a plugin support the functionality.
