### ISSUE TITLE
OpenCollar - lock  bug: open and closed padlocks appear when the collar invisible

### ISSUE THREAD

**Issue by ghost** [OpenCollar/opencollar#58]
when appearance is set to hide, padlocks appear and disappear when the lock / unlock 

Proposed solutions:

integer g_hide ;  // global hide 

SetLockElementAlpha() //EB
{
    if (g_hide) return ;  // ****\* if collar is hide, don't do anything 
...
...
...  
}

changed(integer iChange)
    {
        if (iChange & CHANGED_OWNER)
        {
            llResetScript();
        }
        if (iChange & CHANGED_COLOR)     // ********************\* 
        {
            g_hide = !(integer)llGetAlpha(ALL_SIDES) ;   //check  alpha
            SetLockElementAlpha(); // update hide elements 
        }
    }

**Comment by WendyStarfall** [comment]
This is forever being delayed because of the idea that if locked, we could show/hide a lot more stuff than just lock elements. Imagine that on locked state we get a whole new bunch of fancy stuff to wriggle into the Appearance deal.

This one is annoying me a lot too. Medea said she would look at it soon but probably I will be too impatient to wait out before the 3.940 release which will be this week.
