### ISSUE TITLE
Defalt settings notecard and Label command

### ISSUE THREAD

**Issue by NorthGlenwalker** [OpenCollar/opencollar#59]
It has been reported that the default settings notecard command for setting the label is case sensitive where all other commands in the notecard are not.

Minor bug, as they should be using the dump command to save the format.
Looks like maybe a convert to lower case command is missing in the label script before it processes the command

**Comment by NorthGlenwalker** [comment]
There is another problem in that the dump command sends out User_labe=label~North, when it is looking for User_label=Text~North on the default notecard
This is in 3.937

**Comment by WendyStarfall** [comment]
Alright, I tripple checked that - it sends out the correct dump with Text as indicator. I also get the label loaded back if I use the dump as copypasta and I didn't manage to get the dump line with "label~Wendy". The case sensitivity we need to have case sensitive labels, I'm about 99.998% sure about that one, we need it for variations like wendy/Wendy/WENDY. Closing that one for now because I couldn't get that false dump -> check if the collar you noticed to have it had an old "techlabel" script in it?
