### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by GothAngelBlackheart** [OpenCollar/opencollar#61]
Collar Update not working... Dunno why either... Any suggestions

**Comment by WendyStarfall** [comment]
This is a frequent support request after each major release. I'm sure the creator of your collar will provide an update in form of a full replacement soon.

Some designers choose to give their artwork a (no modify) permission setting. That means they will have to provide full replacement updates from their side because this permission setting will not ever an avatar or a scripted object to write to the collar's contents.

Installing an update is a modification because it changes the software and content like textures, animations and notecards inside of the collar. The good news is that after 3.940 we will no longer send automatic updates and customers who preferred to buy from a 3rd party rather than choosing one of our free stock designs will no longer receive updaters they cannot use.

Third parties who want their own versioning and news system in their collar designs can optionally let us handle this part for them. I think this is an opportunity for designers and businesses to get greater control over how and when they announce updates and also what goes in and what doesn't.
