### ISSUE TITLE
Titler: Empty textbox gets authed CMD_ZERO and sets title "0"

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#629]
> we title box

```
sendernum: 1|num: 0|msg: title box|key: a6d249c9-0aa4-440b-98a6-c92d4bafafac
sendernum: 1|num: 500|msg: title box|key: a6d249c9-0aa4-440b-98a6-c92d4bafafac
sendernum: 1|num: -9000|msg: a6d249c9-0aa4-440b-98a6-c92d4bafafac|
- Submit the new title in the field below.
- Submit a blank field to go back to Titler.|0|||500|key: c173ca8c-2ea8-f1f0-58a4-af783e7cf4e4
```

> Submitting an empty field.

```
sendernum: 1|num: -9001|msg: a6d249c9-0aa4-440b-98a6-c92d4bafafac||0|500|key: c173ca8c-2ea8-f1f0-58a4-af783e7cf4e4
sendernum: 1|num: 2000|msg: titler_title=0|key: 
sendernum: 1|num: 2000|msg: titler_on=1|key: 
sendernum: 1|num: 2000|msg: titler_auth=0|key: 
sendernum: 1|num: -9000|msg: a6d249c9-0aa4-440b-98a6-c92d4bafafac|
Titler

Current Title: 0|0|Set Title`↑ Up`↓ Down`☒ Show`Color|BACK|0|key: 862b3140-0aa0-18a8-3ae3-158691e11ffa
```

> we settings

```
RLVMAIN=on~1
TITLER=title~0~on~1~auth~0
```

**Comment by GarvinTwine** [comment]
OK, i am confused this hasnt come up earlier as this issue should apply to all empty submitted TextBoxes with the Dialog script.
The issue is the DIALOG_RESPONSE (-9001):
a6d249c9-0aa4-440b-98a6-c92d4bafafac||0|500|
this is parsed into a List and then the single values are extracted:

``` LSL
list lMenuParams = llParseString2List(sStr, ["|"], []);
key kAv = (key)llList2String(lMenuParams, 0);
string sMessage = llList2String(lMenuParams, 1);
integer iPage = (integer)llList2String(lMenuParams, 2);
integer iAuth = (integer)llList2String(lMenuParams, 3);
```

But since there is nothing after the first | the "0" after the second | becomes the second entry in the list and the 500 the third which results:
sMessage = "0"
iPage = 500
iAuth = 0 (as there is no entry at this index anymore)

I suggest we replace the empty string in the Dialog script with a " " which should make never sense to use alone for anything and most likely gets eliminated by trim string anyway, but we keep our syntax for dialog response handling and do not have to work around that in every script with text boxes for empty ones.

**Comment by WendyStarfall** [comment]
Yes, please let's do that with the empty string.

EDIT: I didn't see this in Label by the way. Terminal I didn't test yet.

**Comment by GarvinTwine** [comment]
Ok doing this... starting with dialog, #631 we have to check all scripts with TextBoxes:
disgraced_rlv works with the change and doesnt need adjustment.
badwords and boomarks #632
meshlabel #634
titler #633
label #635

**Comment by WendyStarfall** [comment]
I think this is fixed. Thanks, @GarvinTwine !
