### ISSUE TITLE
[Feature] Optional label color in the collar Themes?

### ISSUE THREAD

**Issue by XenHat** [OpenCollar/opencollar#649]
I was wondering if it was possible to add a default label color to the presets located in the .themes notecard, that would be ignored if the collar is using a user-defined label color.

**Comment by GarvinTwine** [comment]
it is not possible without changes the themes script.
If that would be added i think it should override any user-defined label color though, because it is part of that theme the user chooses, if the user then doesnt like the color the theme creator chose for the theme the user can still change it again anyway

**Comment by XenHat** [comment]
Fair enough.
