### ISSUE TITLE
User_rlvmisc

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#65]
1 start with basic collar
2 update it
3 reset it just for the hell of it
4 goto rlv > misc - and forbid all

now goto  options > dump cache

5 Take this line  and paste it into Default settings inside collar        User_rlvmisc=shownames~n~fly~n~fartouch~n~edit~n~rez~n~showinv~n~viewnote~n~viewscript~n~viewtexture~n~showhovertexthud~n~showhovertextworld~n~showhovertext~n

wont restrict the wearer. 

Try same with with say Map/TP or Talk works just fine.

**Comment by WendyStarfall** [comment]
Seems like rlvmisc was left out intentionally. For now, let's add to the user guide that these settings cannot be made permanent defaults. If we get more feedback on people wanting rlvmisc as permanent defaults we can add it. What needs to be considered tho is if a person dumps their cache and adds those settings it may cause them more grief than entertainment if the specific user wasn't 100% sure what they were doing. rlvmisc is in general something that should be an optional plugin rather than part of the standard rlv installation bundle maybe?

**Comment by WendyStarfall** [comment]
Update: RLV Misc is now optional, we leave it exempt from the defaultsettings and put it into the guide. I want to get back with Joy Stipe first if this could be added to defaults. There must be a good reason it was left out and I don't want to introduce new settings bugs after getting it all working so well.
