### ISSUE TITLE
Minor Display Comment

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#654]
Going to the Options menu, the "Size" and "Position" buttons are not addressed in the text at the top.   True they are easy to understand, but it's best to address all the buttons if you're going to address any.  Also, I would mention all buttons the same way.  For example, Print, Load, and Fix are covered by "Print"....  and then "Load".... and then "Fix"...  but Themes and Stealth are listed differently.  I'd recommend all lines be consistent.

Also on Display, the Vulnerable button...  the  word Vulnerable is lower case (vulnerable) but should probably start with an upper case "V" to be consistent with all the other buttons that start with an upper case letter.

**Comment by WendyStarfall** [comment]
The Options menu looks the way it does because that's how I deliberately designed it to appear. :rage:

I feel this way it looks aesthetically pleasing and clearly distinguishes the system specific features for settings and menus from cosmetic features for themes and stealth. The vulnerable option is subject to change because I've not decided on the final name for this mode. I'm tending towards "risky" or "CNC".

**Comment by MystyBoots** [comment]
Ok, but I would still address the "Size" and "Position" buttons so none get left out.

As to what to name the Vulnerable button....  If I understand it (and I'm not sure I do), it takes away the wearer's access to certain collar options.  If that's the case, then "Risky" or "Scary" or something along those lines would be very good.
