### ISSUE TITLE
Locked wearer Not owner and Not Vanilla can change title

### ISSUE THREAD

**Issue by MystyBoots** [OpenCollar/opencollar#656]
Hi.  A person wearing the collar, but is "not" an owner and is "not" in vanilla mode can't access label as expected, but they can change/show/hide their title.  Expected operation would be that the wearer on a locked collar could not change such things.

As a side note, it also seems in this same situation that the wearer can also turn off RLV, which I'd not expect.

**Comment by WendyStarfall** [comment]
When vanilla mode is deactivated by the wearer, they will continue to have the same auth level they already had when accessing dialog menus. That means if they navigate to other menus, they can still use this level of authorization to do stuff like even, turn RLV on or off.

Being able to change and set the title is expected behavior and how it always used to be. A "disgraced" derivative that behaves in a more strict manner will be made available after 4.0 release.

**Comment by MystyBoots** [comment]
It just seems if the "owner" assigns a title "Mysty's Pet" for example, the wearer should not be allowed to hide it or change it.  Just my view :)
