### ISSUE TITLE
***Wearer wrote too much, text discarded***

### ISSUE THREAD

**Issue by HisPhaedra** [OpenCollar/opencollar#66]
On the 3.94 update when using the spyware, my Master is getting that message on big posts to local. This is a BIG problem for para-rp'ers. On the 3.8 version the spyware was perfect .. never had a problem until it just stopped working the other day. Is there anyway to get this fixed?

**Comment by RayZopf** [comment]
The text you see is a fix - else spy addon would just stop to work.
Write less than 450 chars per line, hit enter more often, set radar timer to shorter interval.

...with old SubSpy, complete messages (oldest ones) just were discarded when message buffer grew over 1500 chars before report was sent out.

**Comment by RayZopf** [comment]
see also #54 - did state it there too: 450 chars

**Comment by RayZopf** [comment]
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20subspy.lsl#L67
450 chars
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20subspy.lsl#L669
450 -74 (75) char

and here still is the old code (which, without giving any notice about it, discarded complete messages)
https://github.com/OpenCollar/OpenCollarUpdater/blob/main/LSL/OpenCollar%20-%20subspy.lsl#L687

Tell your Master he either should:
- enforce you to write less than 375 chars without hitting enter
- live with capped messages instead of just discarded ones
- get himself or his sub to write a better spy addon, or to improve the current code

**Comment by WendyStarfall** [comment]
let's see if 944adf2 solved it or if we need to track back and merge stuff back in that might have got overidden; if it sucks, I think it may best to move subspy to the spare parts and distribute it as boxed tinker script from an object vendor at main locations (not through the network)

**Comment by WendyStarfall** [comment]
I made a side to side diff in case the commit diff here is too confusing for some?

http://www.diffchecker.com/6bc07thw

**Comment by RayZopf** [comment]
hm, let me check ... but that will take a while, as it is a big diff and I probably need to make a manual merge.

**Comment by RayZopf** [comment]
here we got the functional code changes (yes the formatting now is ugly, with empty code blocks, etc...)

http://diffchecker.com/43on6lnw
