### ISSUE TITLE
"Release" option under "Runaway" menu (for non-wearers) not working

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#661]
If a temporary owner (kidnap) tries to press the "Release" button under "Runaway," it says "You are not on the access list."

If an owner does this, nothing happens.

In both of these cases, I tested this with no one else (including the wearer) on the access list.

**Comment by WendyStarfall** [comment]
This is because of some leftover 3.9 cruft where various auth roles can asynchronously access a runaway menu for enabling, disabling, running, staying, releasing etc.. 

Temp owners cannot manipulate auth lists as a general rule. They cannot mess around in Access much more than turning group and public modes off and on which is required for [certain role play scenarios](https://en.wikipedia.org/wiki/Gang_bang).

In 4.0 this menu is only for the wearer as only they can "run away". The cruft gets removed, menu gets cleaned up and all others get a `%NOACCESS%` when trying to use a feature that's naturally wearer-only.
