### ISSUE TITLE
Wearer can continue using previous auth level for dialog menu after being kidnapped

### ISSUE THREAD

**Issue by ml132** [OpenCollar/opencollar#662]
When the wearer is kidnapped, they can unleash from the "follow" that is immediately applied. The wearer cannot unleash from subsequent leashing (as intended).

This was tested with no primary owner, and with/without the wearer as secondary owner.

**Comment by WendyStarfall** [comment]
Couldn't reproduce this on OC 4.0/3.6.3 but I will keep observing it.

**Comment by ml132** [comment]
After testing this out again, I was able to reproduce it, but not consistently. I'll see if I can figure out how to reliably reproduce this issue. I am using 4.0/3.6.3

**Comment by GarvinTwine** [comment]
please make sure you have vanilla unchecked.

**Comment by ml132** [comment]
Ok, I figured it out. You can reproduce this issue if the wearer of the collar gets a dialog menu before being kidnapped. If you get a new dialog menu by clicking the collar or using the chat command after being kidnapped, then this works normally.

Here's the procedure:
1. Turn on Kidnap
2. Check Vulnerable
3. (Do not drop this dialog menu)
4. Be kidnapped
5. Navigate menus to leash and unfollow

**Comment by WendyStarfall** [comment]
I see now. That's just because the previous auth level stays with the current dialog menu. It always was this way and the user has to perform a very strange usage flow to end up with 15 more mins of "old auth".

We can address it in a patch past 4.0 release after we saw how new 4.0 menus turn out for most users.

PS: This needs the invalid tag because the issue is not as described in the title. No rudeness intended.

**Comment by WendyStarfall** [comment]
Haha! Thanks! :see_no_evil:
