### ISSUE TITLE
Collar producing (no name) in messages when attempting to do couple animations

### ISSUE THREAD

**Issue by HilaryQ** [OpenCollar/opencollar#672]
When I had the 3.8 collar, when I offered a hug or kiss, I'd get

```
[14:19:50] Hilary
Hilary gives Cwnythryth a sweet kiss.
```

Which came from having my name in the collar description (collarname~3.8~Hilary_)

On upgrading to 3.997, I tried and I get

```
[14:47:35] (no name)
(no name) zài yì 在意 gives Hella Jorgensen a sweet kiss.
```

I tried fixing the description to 3.997 as well, but that had no effect.

Pretty please help.

Using firestorm 4.7.1

**Comment by GarvinTwine** [comment]
It will work just perfect out of the box with 4.0.

**Comment by WendyStarfall** [comment]
You have to uncheck `Mark objects with (no name) when they speak to avoid spoofing`:

![2015-08-18_1228](https://cloud.githubusercontent.com/assets/1100007/9327958/cbe2bc96-45a4-11e5-82c1-697f8fe3b9d3.png)

To the best of my knowledge this setting is not enabled by default in Firestorm 4.7.1. This setting can be useful in extreme cases, when you want to learn the coordinates of a repetitively spamming object.

In a normal situation, it is preferable to use the display name for object emotes and because objects cannot use UTF-8 encoding in Linden's database, we must temporarily remove our object's name for an emote to display as:

`[00:00] 天使 hugs Masterblaster Bimbogami.`

Rather than:

`[00:00] ~*ERF*~Fancy Shmancy Pancy - BuTtFUX RLV Necklace: 天使 hugs Masterblaster Bimbogami.`

The object cannot be called 天使 because the database would return it as: `???`

The name in the collar's root description is in no relation to the couples animator. A correct collar description first uses an item name without space, then adds an ISO 8601 timestamp with a single decimal and finishes with legacy database prefix: `SomeName~YYYYMMDD.n~dbprefix_`

Your collar description is good, it has a real number and an underscore after the database prefix. :cake:

**Comment by WendyStarfall** [comment]
Update on the root description:

This description serves as default global DeviceName in 4.0 versions, the above refers to the 3.9 API.
