### ISSUE TITLE
let's consider to prevent wearers from being added to the trust list

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#749]
Versions: 4.0.0 to 4.0.11

Right now when the wearer is added to the trust list, she would actually lose important wearer specific abilities, such as accessing options or accessing the capture module. Of course it can be explained on the manual that a wearer should never have to be added to the trust list but that may not be sufficient.

I can also see this as being adapted as a "feature" where wearers are deliberately trusted to prevent them from doing certain things. This doesn't have to happen for 4.0.x but we should consider it for 4.1.x

**Comment by GarvinTwine** [comment]
I actually see this as a little bug we somehow missed to clean out in 4.0 and carried over from 3.9 (it behaves there for options the same way, so it is nothing new introduced in 4.0 here) though as this is in place for quite some time already, it can by now be called a feature as well I guess ;).
This only happens at all when there is another owner set, else the wearer gets anyway still authed as owner, no matter if they are trusted or not.

It think nobody noticed this because unlike back in 2008 (where there was only 1 owner) it is uncommon to make the wearer trusted (or secondary owner) as it was back then, nowadays either the wearer becomes owner or just stays wearer... so this is a rather rare case and hasnt been brought to attention for at least the whole 3.9 api (i didnt look back further).

OK, I see 2 ways to deal with this here:
1) dont allow wearer to become trusted
2) make sure it does not matter if a wearer is trusted or what ever for those features that were meant to be wearer/owner (many are this way already, only a few (like options menu) are not)

I tend to 2) and to investigate all scripts about this and change or leave it to the desired way in each individual case.  As I see this as wearer specific features which generally are also granted to owners but not needed to be fiddled with by every trusted, it really should not matter which status the wearer has in the auth system. (in the scripts where this happens you find:
`if (iNum == CMD_OWNER || iNum == CMD_WEARER)`
where it should be:
`if (iNum == CMD_OWNER || kID == g_kWearer)`
So far I only see this in 3 scripts at all:
sys for options menu (where the commands of the menu can be done by the trusted wearer by chat)
boomarks (only for an old no more used reset command)
and capture (again for the capture menu, but the trusted wearer can enable/disable/risky by chat command)

(it is in some more but that's always for the runaway command which is sent internal anyway with CMD_OWNER and not the command callers auth)

**Comment by WendyStarfall** [comment]
I wouldn't call that a bug at all. :speak_no_evil:
It's behaviour as expected if an avatar is assigned to that auth rank. :see_no_evil: 

That will be what 99.998% of seasoned users who add wearers to secondary/trust also expect.

However, in disgraced versions, and large parts of 4.0 are that, the Trusted was supposed to be able to access all role play specific interaction. What isn't role specific are exactly the things that you just listed there. Resetting destinations, manipulating Options, adjusting the fit or really important things where the wearer always retains the ability to interrupt the role play, like it is the case in capture.

The ability that wearers are always able to decide who they trust is new and that's where the dog is buried and how this is coming up now all of a sudden. That's our happy users trying to cheat out of things and ending up with lesser access than they had before (which is actually kind of hilarious).

Suggesting that we don't mess with this until the next major release because even if a user ends up in such a situation, she can still remove herself from the Trust list. During 4.0.x we have to observe how the "new" auth is used by a majority and then adjust that and all features for the next major release at 4.1.x.
