### ISSUE TITLE
fix "while conditions" and use clearer syntax for incrementing and reducing i

### ISSUE THREAD

**Issue by WendyStarfall** [OpenCollar/opencollar#756]
Let's just make such things like `i++;` clearer to understand and fully express it as `i=i+1;`

This is less prone to errors and more easily understood by autodidacts who may not be familiar with C++

**Comment by LiruMouse** [comment]
No offense, but those operators are used in many languages, See https://en.wikipedia.org/wiki/Increment_and_decrement_operators#Supporting_languages
It's even explained on http://wiki.secondlife.com/wiki/LSL_Operators, so anyone learning on their own should know about it.

If anything, a change like this makes the code harder to read and less optimal to run.

**Comment by GarvinTwine** [comment]
To my defence it is not explained at all on http://wiki.secondlife.com/wiki/LSL_Operators but that ++ increments and -- decrements which is kinda obvious. But what is missing is the i++ is a post increment which takes effect only in the next statement but not for the current one. (in difference to ++i).
I dont really see a huge difference in using i++ or i=i+1 and why should it run less optimal ?
Harder to read? That depends on what you are used to read but i=i+1 is very clear to read and understand for everyone I believe.

Anyway, if you think, @Lirusaito ,  you should optimise our code here, be my guest I will read all your optimisation suggestions after my vacation and anything I see as optimised I will try to argue to be included into 4.1 or 5.0 depending on the kind of change you propose :)

**Comment by XenHat** [comment]
![image](https://cloud.githubusercontent.com/assets/980408/11239140/0e645894-8db8-11e5-83ca-984e47f1b706.png)

I also disagree with that change, but it's a code styling opinion.
Performance-wise, both `i++` and `i = i+1` are equivalent, or good enough. _In C++, this would matter more because most compilers are designed to optimize the living hell out of `i++` (aka operator increment), making `i = i+1` slower._
The only real optimization I can see here is that `++i` is faster than `i++`. However, `while` wins over `for`.
_EDIT:Re-worded my thoughts_

**Comment by GarvinTwine** [comment]
and where do you see there that it is a **post** increment?

**Comment by XenHat** [comment]
See edited comment

**Comment by XenHat** [comment]
See http://wiki.secondlife.com/wiki/LSL_Script_Efficiency#Micro-optimization

**Comment by WendyStarfall** [comment]
Most of these loops were redundant and I asked @GarvinTwine to change the style. He isn't the one to blame for this stuff, so please don't think that. I really felt that specifically those errors could have been avoided if we had `i=i+1;` written out prior to the statement which in my opinion felt clearer than `++i;`

**Comment by XenHat** [comment]
No blame on my part. Only striving for the best. :+1: 
I judge the code, not the person who wrote it.

**Comment by WendyStarfall** [comment]
Those mistakes happened after the `i=i+1;` was changed to the C-like variant and erroneously iterated as `i++` in places with code around it. Some contributors must have began copying this without fully understanding the differences in between `++i` and `i++` or even being aware at all that there was such a difference.

I like to believe that the "mistake" is to build code around `i++` where it would be much clearer to understand if it had its own line before the statement. If you said `i=i+1;` or `i+=1;` chances are you usually don't construct code around it.

**Comment by WendyStarfall** [comment]
PS: The "best" in this case is for a large group of people with all kind of skill sets to be able to hack away on things. They can do that and enjoy doing that if the code is clear to read. The changes I asked @GarvinTwine to commit did exactly that. What I just did with d8c4013c71e0249d7deb41d1e59cf3ae961509cd is only relevant to some nerds.

**Comment by SatomiAhn** [comment]
Concerning micro-optimization: most of the referenced wiki page was written in 2007, including the sentence having the word "recently". This was 8 years ago. Did anyone bother to rerun this benchmark more recently ?

For all I know, all of this might as well be completely outdated as of 2015. Also most of it is merely a consequence of implementation choices in the compiler. Newer versions might compile code differently, while still satisfying the specification (and thus, without notifying the crowd of LSL scripters).

Since these are anyway _micro_ optimizations, and they are not even guaranteed to be reliable over time,  my opinion is that readability of code should be prioritized over an hypothetical marginal increase of speed. (This is also usually considered bad practice anyway, except for short critical sections of code, and then you'd better document it well, with all the relevant warnings.)

These were my 2c, now going back to my usual activity of not-doing-much-LSL-anymore. _hugs everybody_
