### ISSUE TITLE
Transmuting 3.997 Mesh collars

### ISSUE THREAD

**Issue by Ariallynn** [OpenCollar/opencollar#882]
Collar: Kibitz Strap Collar Onyx 
Location Purchased: http://maps.secondlife.com/secondlife/Nymphai/196/139/3706
Permissions in inventory: No Transfer
Permissions Rezzed In World: Modify, Copy, No Transfer
Kibitz Collar is 1 object 8 land impact

Issue: After transmuting this collar and repeating to test if it reproduces each time, the leash configure menu button breaks. User will be unable to change the appearance of the leash, the weight or anything within that menu.

Tested the transmuter with another made content creators collar with no menu issues at all. Same version 3.997

Collar: !CD Nuage Open Collar Black
Location Purchased: http://maps.secondlife.com/secondlife/Rebellion/128/128/24
Permissions in Inventory: No Transfer
Permissions Rezzed In World: Modify, Copy, No Transfer
!CD Collar is 1 object 2 land impact

Transmuter version 6.1.0

**Comment by WendyStarfall** [comment]
Duplicates  #881.

**Comment by Ariallynn** [comment]
This was done, early this day. If one of you scriptors would like to see this happen, where a piece of the menu breaks and done so freely. I can tp to a location of your choosing on friday the 18th and rez out the collar in question.

**Comment by WendyStarfall** [comment]
As I'm unable to respond to this on a purely objective basis, let me be a bit more elaborate:

You have introduced yourself to me in-world as a builder avatar of an unknown other party who uses OpenCollar scripts in their items but, as you mentioned in our chat, needs your assistance to build it.

For whatever reason, you never actually disclosed who and what exactly but come here with here-say along the lines "this and that is known to break" and I somehow don't understand what you really need.

Menu buttons or the "Configure" menu in the leash are not "known to break". This is just not true and these things are fully unrelated to the transmutation process, which is an automatic assembly/patch.

Likely there is some funk going on in the particular collar in question but that is not ours to mend. Nobody is going to follow back on these links and buy items from stores that don't contribute to OpenCollar.

When I asked for samples I couldn't have possibly imagined that you would try to link us to the shops of those parties. This can only be a misunderstanding. We are not affiliated with them in some way.

Maybe you were unaware but we share free and open source code, share-alike contents and mostly cost-free, beautiful artwork that runs this stuff perfectly fine. The few products that we actually sell ourselves create just barely enough revenue to make do for the project and small rewards for workers.

I contribute to OpenCollar so that nerds and artsy folks can have fun creating things, sharing things and make each other small gifts. To provide for the commune, not for private entities who want to do business.

This idea that you seem to have where we send one of our "scriptors" to schedule a meeting with you is also, forgive me, really absurd. These products are not our responsibility. Our transmuter device is shared as a courtesy only and worked just fine for thousands of collars. It is known to work very well.

If the transmutation fails for whatever reason, feel free to use API 3.9 or ask the shop owner to assemble a Six for you if that is what they want to do. "Leash Configuration" is a feature that's part of `oc_particle`.

This advice as well as the transmutation device itself, has been shared with you already as a courtesy.

PS: I will excuse myself from this issue and wish to not be contacted about it in-world. I'm aware there are builder kits in the making and I'm happy to see that those are released and well documented. Even then, I will remain on the red side of the board. My love and dedication are just strongest for the free commune.

**Comment by Ariallynn** [comment]
I posted Wendy that none would need to buy these collars. The links were provided because you asked about the previous collar I posted on and how it was a gatcha with wrong permissions.

You may very well be right that the issue stems with the created collar itself.
In my post, I offered to bring both collars I used scripted with the old 3.997 version, to transmute them and then turn there menus over to someone who knows how things are supposed to work.

This way right after the collar is transmuted they could see how ones menu's do not work properly straight after the transmutation process which suggests a bug.

However yet another mesh collar made by a different creator did not have the same issue.

If this is not however anything of worth or note to look into I understand entirely. This can then be closed and I shall refrain from thinking I am trying to help.

I will finish with a small PS of my own, you mentioned in your IMS how you put in the majority of the work and effort to making OC what it is and get very little help from the community..consider this briefly that perhaps the case for that is because when someone new, limited in script knowledge opts to use OC and to test it even on none free collars you are giving back an attitude of feedback like we are unworthy to help you.

**Comment by WendyStarfall** [comment]
I didn't say anything like that.

Everyone who follows [OpenCollar](http://www.opencollar.at/blog) knows well that we mention all contributors by name in every blog post for every release. I have never claimed that I did "the majority of the work" or that I "made OC what it is".

What I said was that I've worked very hard for OpenCollar, that I also paid out of my own pockets to keep places and hosting alive and that I've created a substantial amount of creative content while doing the whole of the project maintenance which can be well reviewed here in the project history.

I have absolutely no issues doing that but I see also no reason why I should do freebie concierge help for some shop owner's builder "alt", who doesn't support us in the slightest and brings here-say to our place.

The problem here is not that others or I would be overstrained with work. The problem is that we indeed do very good work but experience being downgraded by the here-say of individuals who don't do or share anything but merely implement what we create in products that they make for sale but then fail at it.

You will have a hard time turning this around as if you were somehow the victim here. OpenCollar Six is completed, the development is done, the creative content is made and the documentation is written.

Now that it is done anyone could come and pretend having wanted to contribute by other means than scripting all along. I haven't rated you as unworthy and no idea of your skills, as a matter of fact, you are a blank profile, builder "alt" from a virtual world, who didn't even have the decency to show banner.

**Comment by GarvinTwine** [comment]
So, I think it is time that I as the one responsible that there is a transmuter at all gives a final input to these issues.
First of all I created the transmuter because there were many sad people when we had the pre-release (4.0) collar that they were not able to get their beloved collars which have been given to them years ago by friends or whom ever updated to the new improved version of OpenCollar. 
When we released OpenCollar Six I decided to make something that is able to convert old legacy 3.x collars to the new Six API with all its stability and performance advantages.  (Although the common opinion in group chat were it is not possible to do so!)
Now the transmuter is one of the most taken Items OpenCollar offers at the moment, thousands have been taken and used multiple times where there was not one issue reported ever so far.

Then I get told someone might contact me about some weird issue with it... which never happened but instead I read the issue made here on github:

> The update will take, but some of the menu buttons (random which ones) have been known to break and not work. For me it was the leash configure.

So let me first explain here something. 
If one menu button out of (I haven't counted, but maybe 100?) does not work, this is not “breaking” anything, but it means out of some reason one feature out of many does not work when using this menu button. (you haven't even tested if the chat command opens the menu or not here).
Then you state "have been known to break and not work", so far in all your posts in this issues you talk about one collar your tried where this one button did not work and another where all worked... so what is here been known by whom I wonder.

If you, as you state in a later post of yours, would have wanted to help anybody here, you should have gotten the creator of the collar to send one to us with a polite request to check why something seems not fully correct after using a transmuter on her/his collar.
But you just give us links to their stores and tell us when to watch something from the outside which doesn't lead to the slightest form of debugging the “issue” but will maximum confirm what you already said here.

And you opening a second issue (after we dealt with the original one already) where you start to talk about “Mesh Collars” which might lead the reader to the idea this is a general issue about transmuter and mesh collars and not one issue with one collar (mesh or scuplted or legacy prims do not effect the functionality of the transmuter in anyway). But have again only one collar and one menu button to report. 
So this does not really seem to be you trying to help but you trying to troll here because one thing doesn't work for you as you wished, or you just want in general troll about something here.
