### ISSUE TITLE
.settings

### ISSUE THREAD

**Issue by Attitum** [OpenCollar/opencollar#926]
Collar not reading ( ALL of ) .settings file in the settings prim.

seems to read label just fine
LABEL=show~1~text~Some Name  

seams to read  sometimes
GLOBAL=DeviceName~OpenCollar~locked~1

seems to read RARELY or NEVER depending, on if you use reboot vs unwear an wear
RESTRICTIONS=send~500~read~500~talk~500~touch~500~stray~500~rummage~500~dress~500~dazed~500

And occassionately it seems to be picking up settings from an external source.

**Comment by george-black** [comment]
I just experienced the same issue... like 30 seconds ago.  So odd.

I was unable to load settings from the .settings notecard, but loading them from a url worked fine.  That might be a temporary workaround for you.

Edit: Now that I think on it and have experimented a bit:  I was putting the settings notecard in the root prim and not in the storage prim.  Perhaps there was already a .settings in the storage prim, which is why the load appeared to work but the intended settings weren't taking effect.  There is a good chance I'm not having the same problem as you... Maybe no problem at all. I may have just had a minor case of not reading the instructions.

Edit edit:  That's exactly what was happening. Verified.  My "bug" was user error.   I'm gonna leave this here in case anyone else does the same thing 💃

**Comment by Attitum** [comment]
Legend :
xx = prefix 

you can run a little experiment
change your .settings notecard in the bottom prim of the collar (correct not root)
something simple like  lock my collar > GLOBAL=DeviceName~OpenCollar~locked~1
or give my collar a name like > LABEL=show~1~text~Some Name

reboot it and or take off and put it on and or relog on sl.

you will observe that it tends to take the label change mostly immediately, but sometimes it dont and sometimes it takes stuff from like past

u can see what its doing by typing >  XXprint settings

sometimes u will notice hell its even getting settings from a website when it should be getting from  your notecard first

i even ripped out the code blocks  > http_response(key kID, integer iStatus, list lMeta, string sBody)
and below thinking it might force it to only card but was back at orig problem its just not reading each and everytime but sometimes it does surprise you and does do it, but mostly nope.

I suspect this problem is not even in the oc_settings script its comming from else wear to get those values, ive seen this same problem in other versions of the collar, and ive compared the oc_settings script in 613 to 620 and they seem pretty close so its looking like its elsewhere

**Comment by WendyStarfall** [comment]
There is nothing wrong with settings. They basically act the same like in any OpenCollar since the introduction of default setting cards. "Default" because that is what the particular device "defaults to".

In other words: The setting card is loaded once when the user wears the device for the very first time.

From then on the setting card can only be re-loaded with `load card` or (deprecated) `load` commands.

Rebooting, re-wearing and relogging doesn't fetch any settings from the card. If we wanted to restore the device to its defaults each time the user rewears or relogs we wouldn't need to store any settings at all.

The `http_response` event (this block you are referring to) only triggers if we get something in return from a `llHTTPRequest` which in this case only happens when the user enters a valid `load url` command.

The rest of what you describe all sounds very "mysterious" to me but could be a result of arbitrarily "ripping code blocks" from the source? Either that or a gremlin snuck into your collar? :speak_no_evil:

**Comment by xEmpiricalx** [comment]
ah yeahhhhhh!  okay >> There is nothing wrong with settings
There u have it  george-black we just seeing things!  

ah yeahhhhhh!  okay >>  i guess EVA and I on a default collar at OC were seeing things too > The rest of what you describe all sounds very "mysterious" to me but could be a result of arbitrarily "ripping code blocks" from the source? Either that or a gremlin snuck into your collar?
