### ISSUE TITLE
The relay got a error after a relog

### ISSUE THREAD

**Issue by KarinKorpov** [OpenCollar/opencollar#959]
Sometimes.. not whole the time after a relog, get i the error "Stack-Heap Collision" and i understand too that the restriction that was added before the relog not come back when the script oc_relay the error has. 

Is this a bug or something else?

**Comment by WendyStarfall** [comment]
Hi Karin.

To figure this out we need a bit more info. You can print lots of information with the following commands:
- ka info
- ka relay pending
- ka print settings

The settings print will also include your owners in the AUTH category. In case you feel uncomfortable revealing this information, please delete the AUTH line but tell us how many Owners and Trusted avatars you had added, if Vanilla mode was active, as well as whether Public and Group access were enabled.

It will also be necessary to learn if you start your session in a place that has active relay sources, such as furniture, a "zone" or a cage, which might overload your relay plugin with requests until it collides.

The reason you have no restrictions in place from relay sources is because the relay already collided and can't process them. If those are the type of restrictions you always "must" have, I suggest using the 'Legacy RLV Stuff' plugin rather than a relay source that applies them each time you start your SL session.

Unfortunately I'm already spread too thin these days and don't have time to investigate this further myself.

**Comment by KarinKorpov** [comment]
Hi Wendy

**The kk info:**
Model: Cuff Collar 1.3
OpenCollar Version: 6.3.0 (160809.100000)
Origin: Karin (Karin Korpov) 
User: karin.korpov
Prefix: kk
Channel: 1
Safeword: RED
This collar has a homemade core.

**kk relay pending:**
Relay: There are no pending requests.

**kk print settings:**
RLVSYS=on~1
AUTH=trust~9da2c1b0-b265-480e-ac89-d89e6f10008a,a0e6ba36-bae3-477e-b0a0-29fbeb9ea486~owner~ecaaf5f4-6a2c-4b0e-8249-9f4faf88ca62~public~1
GLOBAL=prefix~kk~DeviceName~Cuff Collar 1.3~safeword~RED~locked~1
ANIM=TweakPoseAO~1~PoselockRank~500~animlock~1
LEASH=turn~1~strict~1,500~leashlength~2~leashedto~cc4d1eca-8530-4dcc-804e-b1e55638189c,502,1,0
PARTICLE=C_Texture~Chain~ParticleMode~Classic~Gravity~-1.~Size~<0.07,0.07,1>~Color~<0.000000, 0.000000, 0.000000>~Shine~1~R_Texture~Silk
RLVUNDRESS=smartstrip~1
RLVEX=owner~127~trusted~127
BELL=on~0~show~0~vol~7~sound~6
RELAY=mode~1387

**The restrictions:**
RestrainedLove viewer v3.1.4 (RLVa 2.0.3)

Cuff Collar 1.3 (Spine, child):
  -> detach
  -> fly
  -> temprun
  -> alwaysrun
  -> chatshout
  -> chatnormal
  -> tplm
  -> tploc
  -> tplure
  -> tplure_sec
  -> sittp
  -> tprequest
  -> tplocal:0
  -> addoutfit:jacket
  -> addoutfit:pants
  -> addoutfit:shirt
  -> addoutfit:skirt
  -> addoutfit:undershirt
  -> addoutfit:underpants
  -> showminimap
  -> showloc
  -> showworldmap
  -> showhovertextworld
  -> shownametags
  -> camdistmax:4
  -> tplure:9eaab216-ab61-4b0b-acc6-df698040ae85  [0abby0]
  -> tplure:ecaaf5f4-6a2c-4b0e-8249-9f4faf88ca62  [Karin (Karin Korpov)]
  -> accepttp:ecaaf5f4-6a2c-4b0e-8249-9f4faf88ca62  [Karin (Karin Korpov)]
  -> standtp
  -> showinv
  -> rez
  -> edit
  -> viewnote
  -> viewtexture
  -> viewscript
  -> shownames
  -> fartouch
  -> touchall
  -> startim
  -> camunlock

If you more info needed have, i hear with pleasure of you. And already thanks for take a look.. :)

**Comment by WendyStarfall** [comment]
This is a similar matter to what I've been trying to address in #991. The collar appears to be some type of derivative, it's not coming from the official publisher. This belongs in a help forum or support community.
