### ISSUE TITLE
(Feature Request) Pose-global hover-height setting that does not affect normal standing hover height.

### ISSUE THREAD

**Issue by stawberri** [OpenCollar/opencollar#977]
At the moment, we only have two options for adjusting hover height:
1. Pose specific hover height that adjusts a single pose's height.
2. Global hover height adjustment that adjusts the default height of all poses, _as well as_ the normal hover height outside of any poses (when we're just standing around).

Could we add a third option that that adjusts the default hover height of all poses, but not the normal standing hover height?

**Comment by GarvinTwine** [comment]
I think our idea about the "Global" and pose based hover height is different then you understand it.

Not all poses (ones where the waist point is moved up or down) need height adjustment at all, and if then often not the exact same adjustment but one pose needs more than the other. So to get your pose right, use the adjustment for the pose. 

To adjust the height for each pose is not something you do every day but once for a collar and pose.
This is not meant to be a global setting for poses but for the avatar preference of a hover height.

I will try to explain the idea to have this at all because this is already a rather advanced user setting that only very few need.
Adding one more that seems to do the same at first try but then does not... I fear that will cause more confusion then anything else.

What do we do when a pose is stopped?
We need to reset the hover height again to a default, which in most cases will be 0 (no adjustment).
But now some one uses an avatar that needs a hover height adjustment, as she/he else stands in or a bit above the ground, as we cannot read a hover height setting pre-changing it for the pose, we can only set it back to a default... which would be 0. In those cases the height also fits then right away, the ones that do not need adjustment by users who dont use a adjusted hover height.

So for these users who use a global hover height the global setting is meant to be, they can set their hover height in the anims menu and then, after a collar pose is stopped, their personal global hover height is reset again.

**Comment by stawberri** [comment]
Thank you for explaining.
